### ISSUE TITLE
Get-HPOVBaseline not working with -Version parameter

### ISSUE THREAD

**Issue by daveolker** [HewlettPackard/POSH-HPOneView#371] opened 2018-10-18 17:42 UTC
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
I have uploaded the following SPP to my OneView instance:

```PowerShell
PS> Get-HPOVBaseline

Name        : Service Pack for ProLiant
Version     : 2018.3.0
ISOFileName : P05006_001_spp-2018_03_0-SPP2018030_2018_0226_84.iso
XMLKeyName  : bp003205
BundleSize  : 5.33GB
Locations   : {Internal}
```

My expectation is I should be able to query based on SppName and Version and get the correct result.

### Actual Behavior
```PowerShell
PS> Get-HPOVBaseline -SppName "Service Pack for ProLiant" -Version "2018.3.0"
Get-HPOVBaseline : The Baseline name 'Service Pack for ProLiant' version '2018.3.0' was not found on '15.113.228.175' appliance.
At line:1 char:1
+ Get-HPOVBaseline -SppName "Service Pack for ProLiant" -Version "2018. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (SppName:String) [Get-HPOVBaseline], BaselineResourceException
    + FullyQualifiedErrorId : BaselineResourceNotFound,Get-HPOVBaseline
```
### Steps to reproduce
```PowerShell
PS> Get-HPOVBaseline -SppName "Service Pack for ProLiant" -Version "2018.3.0" -Verbose
VERBOSE: [GET-HPOVBASELINE] Bound PS Parameters: 
Key     Value                    
---     -----                    
SppName Service Pack for ProLiant
Version 2018.3.0                 
Verbose True                     



VERBOSE: [GET-HPOVBASELINE] Called from: <ScriptBlock>
VERBOSE: [GET-HPOVBASELINE] Verify auth
VERBOSE: [TEST-HPOVAUTH] Caller: Get-HPOVBaseline
VERBOSE: [TEST-HPOVAUTH] Verify Auth for 15.113.228.175
VERBOSE: [TEST-HPOVAUTH] $Appliance is [HPOneView.Appliance.Connection]
VERBOSE: [TEST-HPOVAUTH] Received HPOneView.Appliance.Connection Object: 
ConnectionID Name           UserName      AuthLoginDomain Default
------------ ----           --------      --------------- -------
1            15.113.228.175 Administrator LOCAL           True   



VERBOSE: [GET-HPOVBASELINE] Processing AllResourcesInScope.
VERBOSE: [GET-HPOVBASELINE] Scope(s) AllResources is set to 'AllResources'.  Will not add scope to URI query parameter.
VERBOSE: [GET-HPOVBASELINE] SppName Parameter provided: Service Pack for ProLiant
VERBOSE: [GET-HPOVBASELINE] Version Parameter provided: 2018.3.0
VERBOSE: [GET-ALLINDEXRESOURCES] Bound PS Parameters: 
Key                 Value                                                                                                                                            
---                 -----                                                                                                                                            
Uri                 /rest/index/resources?category=firmware-drivers&sort=name:asc&query=fwbaseline_name:'Service Pack for ProLiant' AND fwbaseline_version:'2018.3.0'
ApplianceConnection 15.113.228.175                                                                                                                                   



VERBOSE: [GET-ALLINDEXRESOURCES] Called from: Get-HPOVBaseline
VERBOSE: [GET-ALLINDEXRESOURCES] Processing URI: Get-HPOVBaseline
VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Called from: Get-AllIndexResources
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters: 
Key      Value                                                                                                                                            
---      -----                                                                                                                                            
uri      /rest/index/resources?category=firmware-drivers&sort=name:asc&query=fwbaseline_name:'Service Pack for ProLiant' AND fwbaseline_version:'2018.3.0'
Hostname 15.113.228.175                                                                                                                                   



VERBOSE: [SEND-HPOVREQUEST] Process
VERBOSE: [SEND-HPOVREQUEST] Hostname value: 
ConnectionID Name           UserName      AuthLoginDomain Default
------------ ----           --------      --------------- -------
1            15.113.228.175 Administrator LOCAL           True   



VERBOSE: [SEND-HPOVREQUEST] Processing '15.113.228.175' appliance connection request. 1 of 1
VERBOSE: [SEND-HPOVREQUEST] Requested URI '/rest/index/resources?category=firmware-drivers&sort=name:asc&query=fwbaseline_name:'Service Pack for ProLiant' AND fwbaselin
e_version:'2018.3.0'' to '15.113.228.175'
VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for GET https://15.113.228.175/rest/index/resources?category=firmware-drivers&sort=name:asc&query=
fwbaseline_name:'Service Pack for ProLiant' AND fwbaseline_version:'2018.3.0'
VERBOSE: [RESTCLIENT] Increasing timeout to 10 minutes for '/rest/index/resources?category=firmware-drivers&sort=name:asc&query=fwbaseline_name:'Service Pack for ProLia
nt' AND fwbaseline_version:'2018.3.0''
VERBOSE: [SEND-HPOVREQUEST] Request: GET https://15.113.228.175/rest/index/resources?category=firmware-drivers&sort=name:asc&query=fwbaseline_name:'Service Pack for Pro
Liant' AND fwbaseline_version:'2018.3.0'
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: User-Agent = HPEOneview_PowerShell/4.10 (Microsoft Windows NT 10.0.17134.0)
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: Accept = application/json, text/html, application/xhtml+xml
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: X-API-Version = 800
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 7: auth = [*****REDACTED******]
VERBOSE: [SEND-HPOVREQUEST] Response time: 00:00:00.3950163
VERBOSE: [SEND-HPOVREQUEST] Response Status: 200 (OK)
VERBOSE: [SEND-HPOVREQUEST] Response Header 1: Transfer-Encoding = chunked
VERBOSE: [SEND-HPOVREQUEST] Response Header 2: Cache-Control = no-cache
VERBOSE: [SEND-HPOVREQUEST] Response Header 3: Content-Type = application/json;charset=UTF-8
VERBOSE: [SEND-HPOVREQUEST] Response Header 4: Date = Thu, 18 Oct 2018 17:56:16 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header 5: Server = Apache
VERBOSE: [SEND-HPOVREQUEST] FinalResponse: {"type":"IndexPaginatedCollectionV300","category":"resources","members":[],"created":null,"modified":null,"uri":"/rest/index/
resources?start=0&count=50&sort=name:asc&category=firmware-drivers&query=fwbaseline_name:'Service%20Pack%20for%20ProLiant'%20AND%20fwbaseline_version:'2018.3.0'","prevP
ageUri":null,"nextPageUri":null,"start":0,"count":0,"total":0,"unFilteredTotal":2,"eTag":null}
VERBOSE: [SEND-HPOVREQUEST] Manual Pagination: False
VERBOSE: [SEND-HPOVREQUEST] Response members and automatic pagination
VERBOSE: [SEND-HPOVREQUEST] total stored '0'
VERBOSE: [SEND-HPOVREQUEST] nextPageURI: ''
VERBOSE: [SEND-HPOVREQUEST] Reached End of pagination. Building AllResults
VERBOSE: [SEND-HPOVREQUEST] Cleaning up HttpWebRequest
VERBOSE: [SEND-HPOVREQUEST] Does nextPageUri member exist: True
VERBOSE: [SEND-HPOVREQUEST] Is nextPageUri Null or Empty: True
VERBOSE: [SEND-HPOVREQUEST] Stopping Do/Until loop because nextPageUri is null/empty and have received all objects.
VERBOSE: [SEND-HPOVREQUEST] End
VERBOSE: [GET-ALLINDEXRESOURCES] Done.
VERBOSE: [NEW-ERRORRECORD] Building ErrorRecord object
Get-HPOVBaseline : The Baseline name 'Service Pack for ProLiant' version '2018.3.0' was not found on '15.113.228.175' appliance.
At line:1 char:1
+ Get-HPOVBaseline -SppName "Service Pack for ProLiant" -Version "2018. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (SppName:String) [Get-HPOVBaseline], BaselineResourceException
    + FullyQualifiedErrorId : BaselineResourceNotFound,Get-HPOVBaseline
 
VERBOSE: [GET-HPOVBASELINE] Done.
```

### Version Information
```PowerShell
PS> Get-HPOVVersion

15.113.228.175                      LibraryVersion Path                                                                   
--------------                      -------------- ----                                                                   
ApplianceVersion: 4.10.01.348545.00 4.10.1809.2203 C:\Program Files\WindowsPowerShell\Modules\HPOneView.410\4.10.1809.2203

PS> $PSVersionTable

Name                           Value                                                                                                                                   
----                           -----                                                                                                                                   
PSVersion                      5.1.17134.228                                                                                                                           
PSEdition                      Desktop                                                                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                 
BuildVersion                   10.0.17134.228                                                                                                                          
CLRVersion                     4.0.30319.42000                                                                                                                         
WSManStackVersion              3.0                                                                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                                                     
SerializationVersion           1.1.0.1                              
```

**Comment by ChrisLynchHPE** [comment] 2018-10-31 15:57
This isn't an issue with the installer, rather the API query the Cmdlet is using.

**Comment by ChrisLynchHPE** [comment] 2018-10-31 16:35
@daveolker I am not able to reproduce that behavior:

```PowerShell


[PS] C:\Users\clynch> Get-HPOVBaseline -name "gen10-spp-2018.06 2018 09 18"


Name        : gen10-spp-2018.06 2018 09 18
Version     : 1.1
ISOFileName : bp-gen10spp201806-1-1.iso
XMLKeyName  : bp-5ba0837ab641ed000110bf34
BundleSize  : 1.32GB
Locations   : {Internal}



[PS] C:\Users\clynch> Get-HPOVBaseline -name "gen10-spp-2018.06 2018 09 18" -Version 1.1


Name        : gen10-spp-2018.06 2018 09 18
Version     : 1.1
ISOFileName : bp-gen10spp201806-1-1.iso
XMLKeyName  : bp-5ba0837ab641ed000110bf34
BundleSize  : 1.32GB
Locations   : {Internal}



[PS] C:\Users\clynch> Get-HPOVBaseline -Version 1.1

cmdlet Get-HPOVBaseline at command pipeline position 1
Supply values for the following parameters:
SppName: gen10-spp-2018.06 2018 09 18


Name        : gen10-spp-2018.06 2018 09 18
Version     : 1.1
ISOFileName : bp-gen10spp201806-1-1.iso
XMLKeyName  : bp-5ba0837ab641ed000110bf34
BundleSize  : 1.32GB
Locations   : {Internal}
```

**Comment by ChrisLynchHPE** [comment] 2018-11-25 20:31
After looking at this further, there isn't much else I can do with this.  There are two issues at odds:

* Version based on DateTime, which may include a preceding zero, like your example above
* Version based on semantic versioning, which does not include a preceding or trailing zero, like `1.1`.

`System.Version` truncates preceding zeros, as it isn't relevant to semantic versioning.  So, when a "version" is based on a date and time value, this doesn't work well.  So, if I create a custom class that addresses date time version values, it will break other versions.

If this is a custom baseline, do not use the date time as the version.  If it is a full SPP, there isn't much you can do there.

Not sure how to handle this going forward.

**Comment by daveolker** [comment] 2018-12-07 17:48
I appreciate you investigating the cause so thoroughly.  For now we can close this issue and revisit should the underlying mechanisms change in a way that allows a fool-proof solution in all cases.

**Comment by ChrisLynchHPE** [comment] 2018-12-10 20:36
Okay, closing for now.  We can always revisit this at a later time.

**Closed by ChrisLynchHPE** 2018-12-10 20:36 UTC
Labels: 4.10, Firmware, NeedMoreInformation, UnableToReproduce
