### ISSUE TITLE
Get-HPOVUpLinkSet does not work with -name parameter

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#181] opened 2016-11-17 16:43 UTC
[1611170836_HPOV_transcript.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/597942/1611170836_HPOV_transcript.txt)
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Follow the examples in help
Get-HPOVUplinkSet
Get-HPOVUpLinkSet -name 'FC-A'

### Actual Behavior
Should return list of uplinks or an uplink set object based on name

### Steps to reproduce
Get-HPOVUplinkSet
Get-HPOVUpLinkSet -name 'FC-A'

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.0.1142.2291
HPE OneView Appliance Version:  3.00.01-0268448 
Output from `$PSVersionTable` on your Windows Host:
PSVersion                      5.1.14393.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by ChrisLynchHPE** [comment] 2016-11-17 17:09
I was not able to reproduce this issue in general.  It looks like you do not have any Logical Interconnects that have Uplink Set associated.  Are you trying to get Uplink Set(s) for a Logical Interconnect Group?  If so, the Cmdlet you are trying to use does not support LIGs, as it states in the Cmdlet documentation.  If you are trying to get an Uplink Set for a LIG, then you need to get the LIG, and then look at the `uplinkSets` property of the object.

Although, the Cmdlet is not supposed to generate an error when no Uplink Sets are found without providing the `-Name` parameter.  This was not caught in testing, as the appliances I test with have existing resources defined.  I have found and fixed that issue, and will be in an update.

**Comment by ChrisLynchHPE** [comment] 2016-11-18 23:55
This is fixed in [Release 3.0.1144.2035 ](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1144.2035 ).

Closing.

**Closed by ChrisLynchHPE** 2016-11-18 23:55 UTC
Labels: Bug, Impact - Medium
