### ISSUE TITLE
Synergy Server Template Creation buggy with Mezz Drives

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#225] opened 2017-01-21 21:54 UTC
### Actual Behavior
I've seen a whole bunch of weird behavior attempting to create a server profile template that has drives on Local Storage "Mezz 1 storage controller" of a Synergy Compute Module

a) When I was creating drives on BOTH the 
Integrated storage controller
and Mezz 1 storage controller
If I used the:
New-HPOVServerProfileLogicalDisk -Name <String> [-RAID <String>] [-NumberofDrives <Int32>] [-DriveType <String>] [-Bootable <Boolean>]
form of New-HPOVServerProfileLogicalDisk
The template gets created but when it comes up in the GUI it says JBOD -2 of the Mezz
(and there are no drives on the Mess card)

b) If the drives for Mezz controller are created using the second version of New-HPOVServerProfileLogicalDisk that has -max and mindrivesize
And the DriveType is set to "Auto" with the RAID type set to "RAID1"
The error message complains about HBA?
"New-HPOVServerProfileLogicalDisk : The provide 'HBA' mode does not support assigning of Logical Disks."

c) If I create just Mezz drives and  use RAID1 for the disk mode, two drives, drive type SAS and the  -max and mindrivesize form of 
HPOVServerProfileLogicalDisk 
New-HPOVServerProfileTemplate errors as:
Send-HPOVRequest : The field named bootable near line 1, column 929 is not a valid field in this JSON object. Check the valid fields for this JSON object and remove or correct the unrecognized field.
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.300\HPOneView.300.psm1:63778 char:12
+ ...     $resp = Send-HPOVRequest -uri $uri POST $_spt -appliance $Applian ...

(I don't see that I have "bootable" anywhere on my disks or params hash passed to New-HPOVServerProfileTemplate 

Its there any thing obvious here or anything I can do to make it easier to repo (which out posting masses of code?)

Is there a sample for creating Mezz drives for Synergy?

**Comment by ChrisLynchHPE** [comment] 2017-01-21 21:59
Please provide the script you are trying to execute.  And then please provide the output from -Verbose when you try to create your profile/template

Sent from my Windows 10 phone

**Comment by scriptengine** [comment] 2017-01-22 08:07
<#
    .SYNOPSIS
        Demonstrate the bugs in creating disks on the Mezz connector of
        a Synergy Compute Module

    .NOTES
        jeremy.pack@hpe.com 22 Jan, 2017
#>

#Enforce variable declaration and other PS good practices
Set-PSDebug -Strict
Set-StrictMode -Version latest

#Error Handling
$ErrorActionPreference = "stop"

###
#Setup Basics of Template
#
    $strServerHardwareType = "SY 480 Gen9 1"
    $objHardwareType = Get-HPOVServerHardwareTypes -name $strServerHardwareType -ErrorAction Stop

   #Build params
    $params = @{
        Name               = "DemoMessDiskIssues";
        ServerHardwareType = $objHardwareType;
        EnclosureGroup     = "EG1";
        Firmware           = $false;
        FirmwareMode       = "FirmwareAndSoftware";
        BootMode           = "UEFI";
        PxeBootPolicy      = "IPv4ThenIPv6";
        ManageBoot         = $true ;
        BootOrder          = "HardDisk";
        HideUnusedFlexnics = $true;
        LocalStorage       = $true
        }

###
#Start tests/ Demonstrations
#
write-host "----------------------------------------------------------------------------------------------------------"
write-host "Test 1:`n"

    $strDescription = "Send-HPOVRequest : The field named bootable near line 1, column 840 is not a valid field in this JSON object. Check the valid fields for this JSON object and remove or correct the unrecognized field."

    #Create Logical disks - On Mezz
    $arrStorageControllers = @() #Array controllers used for local storage
    $arrLogicalDisks       = @() #Array of disks for this controller

    $arrLogicalDisks +=  New-HPOVServerProfileLogicalDisk `
                            -Name "MezzDisk1"`
                            -RAID "RAID1" `
                            -DriveType "SAS" `
                            -NumberofDrives 2 `
                            -MaxDriveSize 900 -MinDriveSize 300

    $arrLogicalDisks +=  New-HPOVServerProfileLogicalDisk `
                            -Name "MezzDisk2"`
                            -RAID "RAID1" `
                            -DriveType "SAS" `
                            -NumberofDrives 2 `
                            -MaxDriveSize 900 -MinDriveSize 300

    #Create controller for Mezz
    $arrStorageControllers += New-HPOVServerProfileLogicalDiskController `
                                -ControllerID "Mezz 1" `
                                -Mode "RAID" `
                                -Initialize:$false `
                                -LogicalDisk $arrLogicalDisks

    #Complete Params block
    $params1 = $params.clone()
    $params1["StorageController"] = $arrStorageControllers

    try {
        #Try to create template
        $objOVTask = New-HPOVServerProfileTemplate @params1 -Description $strDescription
        }
    Catch {
        #Catch and output error and then continue to next test
        $Error[0]
        }

write-host "----------------------------------------------------------------------------------------------------------"
write-host "Test 2:`n"

    #"New-HPOVServerProfileLogicalDisk : The provide 'HBA' mode does not support assigning of Logical Disks"

    #Create Logical disks - On Mezz
    $arrLogicalDisks = @() #Array of disks for this controller

    try {
        #Try to create Logical disk as Auto
        $arrLogicalDisks +=  New-HPOVServerProfileLogicalDisk `
                                -Name "MezzDisk1"`
                                -RAID "RAID1" `
                                -DriveType "Auto" `
                                -NumberofDrives 2 `
                                -MaxDriveSize 900 -MinDriveSize 300
        }
    Catch {
        #Catch and output error and then continue to next test
        $Error[0]
        }

write-host "----------------------------------------------------------------------------------------------------------"
write-host "Test 3:`n"

    $strDescription = "JBOD -2 in template"

    #Create Logical disks - On Mezz
    $arrStorageControllers = @() #Array controllers used for local storage

    #Integrated Controller
    $arrLogicalDisks = @() #Array of disks for this controller
    $arrLogicalDisks +=  New-HPOVServerProfileLogicalDisk `
                            -Name "Local1" `
                            -RAID "Raid1" `
                            -Bootable $true `
                            -DriveType "SAS" `
                            -NumberofDrives 2

    $arrStorageControllers += New-HPOVServerProfileLogicalDiskController `
                                -ControllerID "Embedded" `
                                -Mode "RAID" `
                                -Initialize:$false `
                                -LogicalDisk $arrLogicalDisks

    #Mezz Controller
    $arrLogicalDisks = @() #Array of disks for this controller
#
#NOTE: This is the wrong form for New-HPOVServerProfileLogicalDisk Synergy Mezz
#      But it Demonstratest the bug
#
    $arrLogicalDisks +=  New-HPOVServerProfileLogicalDisk `
                            -Name "MezzDisk1"`
                            -RAID "RAID1" `
                            -DriveType "SAS" `
                            -NumberofDrives 2 `
                            -Bootable $false `

    $arrLogicalDisks +=  New-HPOVServerProfileLogicalDisk `
                            -Name "MezzDisk2"`
                            -RAID "RAID1" `
                            -DriveType "SAS" `
                            -NumberofDrives 2 `
                            -Bootable $false `

    #Create controller for Mezz
    $arrStorageControllers += New-HPOVServerProfileLogicalDiskController `
                                -ControllerID "Mezz 1" `
                                -Mode "RAID" `
                                -Initialize:$false `
                                -LogicalDisk $arrLogicalDisks

    #Complete Params block
    $params3 = $params.clone()
    $params3["StorageController"] = $arrStorageControllers

    try {
        #Try to create template
        $blError=$false
        $objOVTask = New-HPOVServerProfileTemplate @params3 -Description $strDescription
        }
    Catch {
        #NO ERROR Expected for Test 3
        $blError=$true
        $Error[0]
        }

    #If profile created with out error ...
    if (!$blError) {
        write-host "Server Profile Template created. Check the profile 'DemoMessDiskIssues' for 'Logical JBODs -2'"
        }

write-host "----------------------------------------------------------------------------------------------------------"
[MezzBugsDemo.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/721790/MezzBugsDemo.txt)

**Comment by scriptengine** [comment] 2017-01-22 08:11
Expected Output (slightly edited in a failed attempt to avoid GitHub mangling it):

PS> .\MezzBugsDemo.ps1
===
Test 1:

Send-HPOVRequest : The field named bootable near line 1, column 1,033 is not a valid field in this JSON object. Check the valid fields for this JSON object and remove or correct the unrecognized field.
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.300\HPOneView.300.psm1:63778 char:12
+ ...     $resp = Send-HPOVRequest -uri $uri POST $_spt -appliance $Applian ...
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [Send-HPOVRequest], InvalidOperationException
    + FullyQualifiedErrorId : InvalidAuthOperation,Send-HPOVRequest

===
Test 2:

New-HPOVServerProfileLogicalDisk : The provide 'HBA' mode does not support assigning of Logical Disks.
At C:\Users\PACKJ\OneDrive - Hewlett Packard Enterprise\powershell\HPEOneView\InfrastrucureAsCode\MezzBugsDemo.ps1:94 char:30
+         $arrLogicalDisks +=  New-HPOVServerProfileLogicalDisk `
    + CategoryInfo          : InvalidArgument: (Mode:String) [New-HPOVServerProfileLogicalDisk], LogicalDiskException
    + FullyQualifiedErrorId : UnsupportedControllerMode,New-HPOVServerProfileLogicalDisk

===
Test 3:

Server Profile Template created. Check the profile 'DemoMessDiskIssues' for 'Logical JBODs -2'
===
PS>

**Comment by scriptengine** [comment] 2017-01-22 08:25
Did that complete my actions?

**Comment by ChrisLynchHPE** [comment] 2017-01-23 19:27
Yes, and I was able to reproduce the issue.  I found and fixed it, which was caused by an incorrect exception message.  When creating a RAID logical disk for the D3940, you must specify a Disk Type.

**Comment by scriptengine** [comment] 2017-01-23 19:40
Great.
>> I found and fixed it
For what for all three examples? 

>>When creating a RAID logical disk for the D3940, you must specify a Disk Type.
Is this in the newer/next version of the code? (Two of my examples [1 & 3] specified SAS)

**Comment by ChrisLynchHPE** [comment] 2017-01-25 00:41
This is fixed in [Release 3.0.1210.3013](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1210.3013).

Closing.

**Closed by ChrisLynchHPE** 2017-01-25 00:41 UTC
Labels: Bug, Impact - Medium, Server Profile Templates, Server Profiles
