### ISSUE TITLE
Show-HPOVUtilization not returning Current Power Value

### ISSUE THREAD

**Issue by storagemike** [HewlettPackard/POSH-HPOneView#562] opened 2021-03-08 09:38 UTC
### Expected Behavior
 Get-HPOVEnclosure | Show-HPOVUtilization should show current, average and peak power readings.

### Actual Behavior
 Get-HPOVEnclosure | Show-HPOVUtilization
[Get-HPOVEnclosure Show-HPOVUtilization.txt](https://github.com/HewlettPackard/POSH-HPEOneView/files/6100331/Get-HPOVEnclosure.Show-HPOVUtilization.txt)
 only returns values for average and peak. Current always returns a 0 value

```powershell
Name                      : NFV-COMPUTE-117
Uri                       : /rest/enclosures/09CZ20070G4F
PowerCurrent              : 0 W
PowerAverage              : 2,521 W
PowerPeak                 : 2,544 W
AmbientTemperature        : 19.00 °C
AmbientTemperatureAverage : 20.00 °C
LastUpdated               : 08/03/2021 02:50:00
PollingInterval           : 00:05:00
ApplianceConnection       : 10.57.160.10
```
### Steps to reproduce
Get-HPOVEnclosure | Show-HPOVUtilization

```PowerShell
See attached
```

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`):
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  
Output from `$PSVersionTable` on your Windows Host:

```PowerShell
# Output from $PSVersionTable
```

PS C:\Windows\system32> Get-HPOVVersion

10.57.160.10                        LibraryVersion Path
------------                        -------------- ----
ApplianceVersion: 5.00.02.418011.00 5.0.2597.2846  C:\Program Files\WindowsPowerShell\Modules\HPOneView.500\5.0.2597.2846

PS C:\Windows\system32> Get-HPOVVersion -ApplianceVer

10.57.160.10                        LibraryVersion Path
------------                        -------------- ----
ApplianceVersion: 5.00.02.418011.00 5.0.2597.2846  C:\Program Files\WindowsPowerShell\Modules\HPOneView.500\5.0.2597.2846

PS C:\Windows\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by ChrisLynchHPE** [comment] 2021-03-08 19:31
What enclosure type is this?  c-Class or Synergy?  If Synergy, this isn't a bug, just not implemented at this time.  If c-Class, then there is no way to get the current power allocation from OneView, and this would be as designed.

**Comment by ChrisLynchHPE** [comment] 2021-03-08 21:41
Also, for HPE Synergy enclosures, the Current Power Allocation is a property of the enclosure resource itself:

```powershell
[PS] C:\Users\clynch> Get-OVEnclosure -Name encl-1 | Select powerAllocatedWatts, powerAvailableWatts, powerCapacityWatts


powerAllocatedWatts powerAvailableWatts powerCapacityWatts
------------------- ------------------- ------------------
               1111                7929               7950

```

**Comment by ChrisLynchHPE** [comment] 2022-07-19 18:12
This was duplicated by #595.  

Closing due to no further activity.  If you wish, feel free to re-open to discuss further.

**Closed as completed by ChrisLynchHPE** 2022-07-19 18:12 UTC
Labels: Enhancement, Question, Enclosures
