### ISSUE TITLE
Strange behaviour of Connect-HPOVMgmt

### ISSUE THREAD

**Issue by CermakPOI** [HewlettPackard/POSH-HPOneView#175] opened 2016-10-04 07:17 UTC
When i try to connect and the connection is already existing the script is terminated.
### Expected Behavior
Return an result Object instead on nothing, telling me i'm already connected and go on with the following code.

```
$objHPOVConnection = Connect-HPOVMgmt -Hostname "11.111.11.11" -AuthLoginDomain local -UserName Administrator -Password 'MyPwd'  -ErrorAction SilentlyContinue
WARNING: You are already connected to 11.111.11.11
write-host "Result of connection: $($objHPOVConnection.Message)  -- $($objHPOVConnection.connected)"
Result of connection: You are already connected to 11.111.11.11
```
Powershell output:
WARNING: You are already connected to 11.111.11.11
Result of connection: You are already connected to 11.111.11.11 -- True

### Actual Behavior
Return nothing and just stops executing the following code.
```
$objHPOVConnection = Connect-HPOVMgmt -Hostname "11.111.11.11" -AuthLoginDomain local -UserName Administrator -Password 'MyPwd'  -ErrorAction SilentlyContinue
WARNING: You are already connected to 11.111.11.11
write-host "Result of connection: $objHPOVConnection"

```
Powershell output:
WARNING: You are already connected to 11.111.11.11
[following code is NOT Executed]
So before making a connection i have to check the global variable ($ConnectedSessions) and if it contains something i skip the connection.

### Steps to reproduce
```
$objHPOVConnection = Connect-HPOVMgmt -Hostname "11.111.11.11" -AuthLoginDomain local -UserName Administrator -Password 'MyPwd'  -ErrorAction SilentlyContinue
WARNING: You are already connected to 11.111.11.11
write-host "Result of connection: $objHPOVConnection"

```

### Version Information
HPE OneView PowerShell Library Version (Get-HPOVVersion): 2.0.621.0
HPE OneView Appliance Version: 2.00.02-0219211
Output from $PSVersionTable on your Windows Host:
Name : PSVersion
Value : 4.0

Name : WSManStackVersion
Value : 3.0

Name : SerializationVersion
Value : 1.1.0.1

Name : CLRVersion
Value : 4.0.30319.42000

Name : BuildVersion
Value : 6.3.9600.17400

Name : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0}

Name : PSRemotingProtocolVersion
Value : 2.2

**Comment by ChrisLynchHPE** [comment] 2016-10-04 15:59
There is nothing in the `Connect-HPOVMgmt` Cmdlet code that prevents any scripts from running if you have an existing connection.  Can you post a sample of your script that you are trying to run?

**Comment by ChrisLynchHPE** [comment] 2016-10-27 05:28
Closing this issue due to no further activity and unable to reproduce.  If you are still running into this issue, please open a new issue and provide your script.

**Closed by ChrisLynchHPE** 2016-10-27 05:28 UTC
