### ISSUE TITLE
Get-HPOVServerProfile HPOV 4.20 bug report

### ISSUE THREAD

**Issue by dijsselhof** [HewlettPackard/POSH-HPOneView#487] opened 2020-07-09 15:15 UTC
### Expected Behavior on OneView 4.20 instance
Get-HPOVServerProfile should give a reproducable command without any errors also on a DL proliant server

### Actual Behavior
Get-HPOVServerProfile produces this : 

```powershell
New-HPOVServerProfile -Name $name -Description $description -AssignmentType Server -Server $server -ManageConnections $False -LocalStorage -StorageController $controllers -ManageBoot:$manageboot -BootMode $biosBootMode -BootOrder $bootOrder. 
```

If you place this back in another OneView 4.20 instance the following error occurs: 

```powershell
New-HPOVServerProfile : A parameter cannot be found that matches parameter name 'ManageConnections'.
At C:\intel\sdnlvdc00103profile.ps1:28 char:100
+ ... ion -AssignmentType Server -Server $server -ManageConnections $False  ...
+                                                ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-HPOVServerProfile], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-HPOVServerProfile
```
Removing the "-ManageConnections $False" part makes the script work without an error 

### Steps to reproduce
Get-HPOVServerProfile
put the output into another OneView instance reproduces the error

**Comment by ChrisLynchHPE** [comment] 2020-07-30 01:57
You mean this is happening when you use ConvertTo-HPOVPowerShellScript, correct?  Get-HPOVServerProfile does not generate any script code you provided.  The 4.20 library is no longer supported.  Can you please update your library and OneView to either 5.00 or 5.20?  The 5.20 and 5.30 library have this fixed, if the issue is with ConvertTo-HPOVPowerShellScript Cmdlet.

**Comment by ChrisLynchHPE** [comment] 2021-02-09 23:05
Closing due to no further activity.  If you feel this is in error, please feel free to reopen this issue.

**Closed as completed by ChrisLynchHPE** 2021-02-09 23:05 UTC
Labels: Bug, NeedMoreInformation
