### ISSUE TITLE
Add-HPOVBaseline - "You cannot call a method on a null-valued expression."

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#161] opened 2016-08-01 12:54 UTC
### Expected Behavior
1) Add-HPOVBaseline -File filepath
2) Baseline uploaded to Firmware Repository

### Actual Behavior
1) Add-HPOVBaseline -File filepath
2) Add-HPOVBaseline : "You cannot call a method on a null-valued expression"

### Steps to reproduce
Add-HPOVBaseline -File filepath

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.576.0
HPE OneView Appliance Version: 2.00.07

**Comment by ChrisLynchHPE** [comment] 2016-08-01 17:36
This is caused by some verbose reporting that I added after testing the Cmdlet functionality.  I'll have this fixed.

**Comment by ChrisLynchHPE** [comment] 2016-08-09 22:27
This is fixed in [Release 2.0.604.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.604.0).

Closing.

**Comment by erikgraa** [comment] 2016-08-10 11:01
I'm getting the same error as before, with 2.0.604.0

Add-HPOVBaseline -File FullPath.iso

It stops right after:

VEBOSE: Checking if baseline exists.
.... you cannot call a method on a null-valued expression.
.. at HPOneView.200.psm1 line 13471

**Comment by ChrisLynchHPE** [comment] 2016-08-10 16:35
Use the following as a workaround for now:

```PowerShell
Get-ChildItem FullPath.iso | Add-HPOVBaseline
```

It appears that an elseif statement is missing that should have taken care of the `-File` parameter being a `String` value.  I'll reopen this issue and release an update to address it.

**Comment by erikgraa** [comment] 2016-08-11 11:39
Great! :)

**Comment by ChrisLynchHPE** [comment] 2016-08-20 03:09
The regression has been fixed.  Please update to [Release 2.0.610.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.610.0).  Closing.

**Closed by ChrisLynchHPE** 2016-08-20 03:09 UTC
Labels: Bug
