### ISSUE TITLE
Get-HPOVBaseline Duplicate Key Error

### ISSUE THREAD

**Issue by j-crawford17** [HewlettPackard/POSH-HPOneView#574] opened 2021-07-06 19:35 UTC
When running the Get-HPOVBaseline commandlet, I'll get the following error

```
Get-HPOVBaseline : Cannot convert the JSON string because a dictionary that was converted from the string contains the
duplicated keys 'HPE Ethernet 100Gb 2-Port QSFP56 MCX623106AS-CDAT Adapter' and 'HPE Ethernet 100Gb 2-port QSFP56
MCX623106AS-CDAT Adapter'.
At line:1 char:18
+ $sppCollection = Get-HPOVBaseline
+                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-HPOVBaseline], InvalidOperationException
    + FullyQualifiedErrorId : DuplicateKeysInJsonString,Get-HPOVBaseline
```

Using Module - HPOneview.500
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      2736   1630
```

Error only occurs on OneView 5.00.02. Seems to run fine on OneView 5.30 and above.

**Comment by ChrisLynchHPE** [comment] 2021-07-06 20:51
This is caused by the SPP/SSP containing multiple, duplicate keys, which PowerShell/C# does not allow.  Yes, this is fixed in newer versions of the library.  Unfortunately, the 5.00 library is no longer supported here.  Please update your use of the library and OneView to a current release.

**Comment by jacobhopkins117** [comment] 2021-07-07 13:33
Hey Chris - Unfortunately we're currently blocked from upgrading beyond 5.00 due to [a00101430en_us](https://support.hpe.com/hpesc/public/docDisplay?docId=a00101430en_us&docLocale=en_US) until our engineers can finalize upgrading the Emulex firmware on hundreds of production systems. Are you aware of a workaround to get our ~300 Server Profile Templates modified?

**Comment by ChrisLynchHPE** [comment] 2021-07-07 19:01
Yes.  You can always natively edit the resource objects directly.  For instance, use the following:

```powershell
$BaselinesUri = "/rest/firmware-drivers"
$Baselines = Send-HPOVRequest -Uri $BaselinesUri

$Baseline = $Baselines.members | Where name -eq "Baseline Name"

$SPT = Get-HPOVServerProfileTemplate -Name MyTemplateName

$SPT.firmware.firmwareBaselineUri = $Baseline.uri

# Specify one value:  "FirmwareOnly", "FirmwareAndOSDrivers", or "FirmwareOnlyOfflineMode"
$SPT.firmware.firmwareInstallType = "FirmwareOnly"
$SPT.firmware.firmwareActivationType = "Immediate"
Save-HPOVServerProfileTemplate -InputObject $SPT | Wait-HPOVTaskComplete
```

**Comment by jacobhopkins117** [comment] 2021-07-07 21:05
Great! Thank you for the follow up.

**Comment by ChrisLynchHPE** [comment] 2022-06-22 20:45
Closing due to no further activity.

**Closed as completed by ChrisLynchHPE** 2022-06-22 20:45 UTC
Labels: 5.00
