### ISSUE TITLE
New-HPOVBackup Errors

### ISSUE THREAD

**Issue by CermakPOI** [HewlettPackard/POSH-HPOneView#49] opened 2015-12-17 11:31 UTC
Starting in lineno 11183

Here the basic corrections:
_ApplianceConnection is not in the Object_

$_Connection.ApplianceConnection.Name => $_Connection.Name

_Typo in Variable Name:_
$backupFileUri => $_backupFileUri

**Old code**
```powershell
			$_backupUri     = (Send-HPOVRequest $_taskStatus.uri -Hostname $_Connection).associatedResource.resourceUri
			$_backupFileUri = (Send-HPOVRequest $_backupUri -Hostname $_Connection.ApplianceConnection.Name).downloadUri
            
			Write-Verbose "[$($MyInvocation.InvocationName.ToString().ToUpper())] Backup File URI $($backupFileUri)"

			#Now that the Support Dump has been requested, download the file
            Write-Verbose "[$($MyInvocation.InvocationName.ToString().ToUpper())] Downloading $($backupFileUri) to $($Location)"

			Try
			{

				Download-File $backupFileUri $_Connection $Location

			}
```		    

**Corrected Code**

```powershell
			$_backupUri     = (Send-HPOVRequest $_taskStatus.uri -Hostname $_Connection).associatedResource.resourceUri
			$_backupFileUri = (Send-HPOVRequest $_backupUri -Hostname $_Connection.Name).downloadUri
            
			Write-Verbose "[$($MyInvocation.InvocationName.ToString().ToUpper())] Backup File URI $($backupFileUri)"

			#Now that the Support Dump has been requested, download the file
            Write-Verbose "[$($MyInvocation.InvocationName.ToString().ToUpper())] Downloading $($backupFileUri) to $($Location)"

			Try
			{

				Download-File $_backupFileUri $_Connection $Location

			}
```

**Comment by ChrisLynchHP** [comment] 2015-12-17 17:42
This is a duplicate of #46 and has already been fixed in an internal build.  A new release is scheduled for tomorrow (Friday US Pacific).  Closing issue.

**Closed by ChrisLynchHP** 2015-12-17 17:42 UTC
Labels: bug, duplicate
