### ISSUE TITLE
Connect-HPOVMgmt - no longer accepts hostname without specifying -hostname/-appliance

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#257] opened 2017-03-22 10:41 UTC
Connect-HPOVMgmt no longer accepts hostname without specifying -hostname/-appliance. "A positional parameter cannot be found that accepts <fqdn>".

Connect-HPOVMgmt <fqdn>

HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.0.1264.2779
HPE OneView Appliance Version:   3.0
Output from `$PSVersionTable` on your Windows Host: 4.0

**Comment by ChrisLynchHPE** [comment] 2017-03-22 15:12
This is by design and notification was made in the first releases of the 3.00 library release notes.  Positional parameter declaration has been removed from the library.  You will need to update your scripts to add the parameter names.

**Comment by erikgraa** [comment] 2017-03-22 15:13
OK. 👍

**Comment by ChrisLynchHPE** [comment] 2017-03-22 16:15
Closing.

**Closed by ChrisLynchHPE** 2017-03-22 16:15 UTC
