### ISSUE TITLE
New-HPOVServerProfileLogicalDisk and -DriveType parameter

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#190] opened 2016-12-19 20:39 UTC
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
The help of New-HPOVServerPRofileLogicalDisk provide documentation of -DriveType as follow:
 -DriveType [<String>]
     Defines the interface type for drives that will be used to build the logical drive. Supported values depend on the local storage capabilities of the selected server hardware type.
It does NOT provide list of possible values. However, when you specify SASHdd it returns an error as follow

"New-HPOVServerProfileLogicalDisk : Cannot validate argument on parameter 'DriveType'. The argument "SasHdd" does not belong to the set "SAS,SATA,SASSSD,SATASSD,Auto" specified by the ValidateSet attribute. "

So it has a set of pre-defined values. 

Feedback #1: I suggest to update the help file to provide those recommended values

Feedback #2: when looking for storagecapabilities.driveTechnologies, I notice that values are: SasHdd, SataHdd, SasSsd, SataSsd
So can the POSH Library use the same values as defined in the attributes?

Feedback #3 : What is the purpose of ' Auto'? . The -DriveType parameter is not mandatory, so if not specified, should the cmdlet produce default value?

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.0.1170.1173

HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:

**Comment by ChrisLynchHPE** [comment] 2016-12-19 21:02
> Feedback #1: I suggest to update the help file to provide those recommended values
I'll get that into a help update soon.

> Feedback #2: when looking for storagecapabilities.driveTechnologies, I notice that values are: SasHdd, SataHdd, SasSsd, SataSsd
> So can the POSH Library use the same values as defined in the attributes?

This is by design and to follow the UI.

> Feedback #3 : What is the purpose of ' Auto'? . The -DriveType parameter is not mandatory, so if not specified, should the cmdlet produce default value?

This is by design and to follow the UI.

**Comment by DungKHoang** [comment] 2016-12-20 00:23
Feedback # 2 : The UI does say SAS HDD, SATA Hdd...

![ld](https://cloud.githubusercontent.com/assets/9196456/21333792/5e509e34-c607-11e6-8851-c31fba7867ca.PNG)

Feedback #3 : There is no ' Auto' option but 'Not Specified ' option

**Comment by ChrisLynchHPE** [comment] 2017-01-05 00:36
Do you really want to be typing in HDD?  The `-DriveType` parameter values are not going to change.

Auto = Not Specified.  It's easier to type in Auto.

**Comment by ChrisLynchHPE** [comment] 2017-01-05 00:38
Linking with #203 for documentation update.

**Comment by ChrisLynchHPE** [comment] 2017-01-05 04:18
This is fixed in [Release 3.0.1191.2858](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1191.2858) and updated help (use `Update-Help` cmdlet to update existing installs with the new help).

Closing.

**Closed by ChrisLynchHPE** 2017-01-05 04:18 UTC
Labels: Question
