### ISSUE TITLE
Get-HPOVServerProfile -InputObject $server without profile, returns all profiles instead of null

### ISSUE THREAD

**Issue by davidvf** [HewlettPackard/POSH-HPOneView#423] opened 2019-10-22 14:04 UTC
Hi,

When I run Get-HPOVServerProfile for a server object, that has no profile, i get all profiles back for systems with the same server hardware type.

### Expected Behavior
It should not return anything

### Actual Behavior
![2019-10-22 15_49_34-Window](https://user-images.githubusercontent.com/1881071/67292686-a08f2500-f4e3-11e9-9a5d-f201b826c378.png)

### Steps to reproduce
`$server = Get-HPOVServer -name serverWithoutProfile`
`Get-HPOVServerProfile -InputObject $server`

### Version Information
`PS C:\Users\vanfroda> Get-HPOVVersion`

`LibraryVersion Path`
`-------------- ----`
`5.0.2152.1665  C:\Program Files\WindowsPowerShell\Modules\HPOneView.500\5.0.2152.1665`

`PS C:\Users\vanfroda> Get-HPOVVersion -ApplianceVer`

`gsdova01.bel1.global.tslabs.hpecorp.net LibraryVersion Path`
`--------------------------------------- -------------- ----`
`ApplianceVersion: 5.00.00.400525.00     5.0.2152.1665  C:\Program Files\WindowsPowerShell\Modules\HPOneView.500\5.0....`

`PS C:\Users\vanfroda> $PSVersionTable`

`Name                           Value`
`----                           -----`
`PSVersion                      5.1.18362.145`
`PSEdition                      Desktop`
`PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}`
`BuildVersion                   10.0.18362.145`
`CLRVersion                     4.0.30319.42000`
`WSManStackVersion              3.0`
`PSRemotingProtocolVersion      2.3`
`SerializationVersion           1.1.0.1`

**Comment by ChrisLynchHPE** [comment] 2019-12-04 00:23
Sorry for the late reply to this.  The behavior you are seeing is by design.  If you are trying to see if a server hardware resource is assigned to a profile, you are using this Cmdlet combination incorrectly.  You should instead do the following:

```powershell
# Get the server object
$Server = Get-HPOVServer -Name serverWithoutProfile

# Check to see if the server has an assigned profile
if ([String]::IsNullOrEmpty($Server.serverProfileUri)) {

   # Server is not assigned a profile, do something

}
```

**Comment by ChrisLynchHPE** [comment] 2020-01-14 20:33
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.

**Closed as completed by ChrisLynchHPE** 2020-01-14 20:33 UTC
Labels: Question
