### ISSUE TITLE
Get-HPOVSanManager unable to properly get object using -SanManager switch

### ISSUE THREAD

**Issue by aricbernard** [HewlettPackard/POSH-HPOneView#44] opened 2015-12-05 05:46 UTC
C:\> Get-HPOVSanManager
Name                        State Type                      Version   Managed SANs
----                        ----- ----                      -------   ------------
**172.28.10.37**                Ready Brocade Network Advisor   12.4.1.23 {ssan01, ssan02}
Local Direct Attach Manager Ready Direct Attach SAN Manager 2.0.0     None

PS C:\> Get-HPOVSanManager -SanManager "**172.28.10.37**" -Verbose
VERBOSE: [GET-HPOVSANMANAGER] Getting list of SAN Managers
VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters:
Key   : uri
Value : /rest/fc-sans/device-managers?sort=name:asc
VERBOSE: [SEND-HPOVREQUEST] SSLCheckFlag: True
VERBOSE: [SEND-HPOVREQUEST] Requested URI: /rest/fc-sans/device-managers?sort=name:asc
VERBOSE: [SEND-HPOVREQUEST] PROCESS
VERBOSE: [RESTCLIENT] Bound PS Parameters:
Key    Value
---    -----
method GET
uri    /rest/fc-sans/device-managers?sort=name:asc
VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for GET
https://**172.28.10.1**/rest/fc-sans/device-managers?sort=name:asc
VERBOSE: [SEND-HPOVREQUEST] Request: GET https://**172.28.10.1**/rest/fc-sans/device-managers?sort=name:asc
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Accept = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: X-API-Version = 120
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: auth = o5dhMmFdm6IOxZBsrMo6HuWMXM5AYWVT
VERBOSE: [SEND-HPOVREQUEST] Response Status: 200 OK
VERBOSE: [SEND-HPOVREQUEST] Response Header 1: Vary = Accept-Encoding
VERBOSE: [SEND-HPOVREQUEST] Response Header 2: Content-Encoding =
VERBOSE: [SEND-HPOVREQUEST] Response Header 3: Transfer-Encoding = chunked
VERBOSE: [SEND-HPOVREQUEST] Response Header 4: Cache-Control = no-cache
VERBOSE: [SEND-HPOVREQUEST] Response Header 5: Content-Type = application/json; charset=utf-8
VERBOSE: [SEND-HPOVREQUEST] Response Header 6: Date = Fri, 04 Dec 2015 22:45:03 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header 7: Via = 1.1 hponeview.customer1.host.local
VERBOSE: [SEND-HPOVREQUEST] Response Header 8: X-Powered-By = ServiceStack/3.960 Unix/Mono
VERBOSE: [SEND-HPOVREQUEST] Response:

members      : {@{uri=/rest/fc-sans/device-managers/2afaa7e9-0cbf-4e29-b1c1-1f03013a87a1; name=**172.28.10.37**;
               type=FCDeviceManagerV2; state=Ready; status=OK; category=fc-device-managers;
               connectionInfo=System.Object[]; created=2015-12-04T22:40:50.145Z; description=Brocade Network Advisor;
               deviceManagerUrl=https://**172.28.10.37**:443/dcm-client/dcmclient.jnlp?module=Main;
               deviceManagerVersion=12.4.1.23; eTag=217ecfba-d119-425f-a62d-e5102df89d97; isInternal=False;
               managedSansUri=/rest/fc-sans/device-managers/2afaa7e9-0cbf-4e29-b1c1-1f03013a87a1/managed-sans;
               modified=2015-12-04T22:40:51.747Z; providerDisplayName=Brocade Network Advisor;
               providerUri=/rest/fc-sans/providers/0aa1f4e1-3b5e-4233-af1a-f849dc64da69; refreshState=Stable;
               unimportedSansUri=/rest/fc-sans/device-managers/2afaa7e9-0cbf-4e29-b1c1-1f03013a87a1/unimported-sans},
               @{uri=/rest/fc-sans/device-managers/09fb14a3-3cb7-437f-b71a-ec865dc01d62; name=Local Direct Attach
               Manager; type=FCDeviceManagerV2; state=Ready; status=OK; category=fc-device-managers;
               connectionInfo=System.Object[]; created=2015-10-23T17:45:58.460Z; description=Direct Attach SAN
               Manager; deviceManagerUrl=; deviceManagerVersion=2.0.0; eTag=406a2dc8-37d6-43c3-bf3d-170dfc296d0c;
               isInternal=True;
               managedSansUri=/rest/fc-sans/device-managers/09fb14a3-3cb7-437f-b71a-ec865dc01d62/managed-sans;
               modified=2015-12-04T21:53:14.749Z; providerDisplayName=Direct Attach SAN Manager;
               providerUri=/rest/fc-sans/providers/5c5c67f5-0f8f-4c85-a54f-f26b1f1332c7; refreshState=Stable;
               unimportedSansUri=/rest/fc-sans/device-managers/09fb14a3-3cb7-437f-b71a-ec865dc01d62/unimported-sans}}
start        : 0
count        : 2
total        : 2
firstPageUri :
lastPageUri  :
prevPageUri  :
nextPageUri  :
VERBOSE: [SEND-HPOVREQUEST] Manual Pagination: False
VERBOSE: [SEND-HPOVREQUEST] END
VERBOSE: [GET-HPOVSANMANAGER] Requested Managed SAN '**172.28.10.37**' not found.
VERBOSE: [NEW-ERRORRECORD] Building ErrorRecord object
Get-HPOVSanManager : Request SAN Manager '**172.28.10.37**' not found.  Please check the name and try again.
At line:1 char:1
+ Get-HPOVSanManager -SanManager "**172.28.10.37**" -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-HPOVSanManager:String) [Get-HPOVSanManager], InvalidOperationExcept
   ion
    + FullyQualifiedErrorId : SanManagerResourceNotFound,Get-HPOVSanManager

**Comment by aricbernard** [comment] 2015-12-05 05:49
Also note that this also affects passing objects on the pipeline such as the following example:
Get-HPOVSanManager | ? Name -NE "Local Direct Attach Manager" | Remove-HPOVSanManager

**Comment by ChrisLynchHP** [comment] 2015-12-07 19:04
I found the cause of the first problem.  There is an internal filter to look for the SanManager provided by the caller, and was using the wrong value.  Can you provide more detail on what is affected when you try to filter objects in the pipeline?

**Comment by aricbernard** [comment] 2015-12-07 19:25
In short, whatever object is being passed by Get-HPOVSanManager  (assuming there was one) is not being handled properly by Remove-HPOVSanManager.

Get-HPOVSanManager| ? Name -NE "Local Direct Attach Manager" | Remove-HPOVSanManager -Confirm:$false -Verbose 

VERBOSE: [REMOVE-HPOVSANMANAGER] SanManager Parameter is 'System.Management.Automation.PSCustomObject' type.
VERBOSE: [REMOVE-HPOVSANMANAGER] SanManager contains  items.
VERBOSE: [REMOVE-HPOVSANMANAGER] Processing '172.28.10.37'
VERBOSE: Performing the operation "Remove SAN Manager from appliance?" on target "172.28.10.37".
VERBOSE: [REMOVE-HPOVRESOURCE] Called from: Internal
VERBOSE: [REMOVE-HPOVRESOURCE] Resource name provided:
@{uri=/rest/fc-sans/device-managers/a283d916-8dfd-46a0-a264-a06fa0aaed03; name=172.28.10.37; type=FCDeviceManagerV2;
state=Ready; status=OK; category=fc-device-managers; connectionInfo=System.Object[]; created=2015-12-02T22:38:53.792Z;
description=Brocade Network Advisor; deviceManagerUrl=https://172.28.10.37:443/dcm-client/dcmclient.jnlp?module=Main;
deviceManagerVersion=12.4.1.23; eTag=60a93713-908f-4d96-b168-99fbbae98f9e; isInternal=False;
managedSansUri=/rest/fc-sans/device-managers/a283d916-8dfd-46a0-a264-a06fa0aaed03/managed-sans;
modified=2015-12-04T22:28:15.008Z; providerDisplayName=Brocade Network Advisor;
providerUri=/rest/fc-sans/providers/0aa1f4e1-3b5e-4233-af1a-f849dc64da69; refreshState=Stable;
unimportedSansUri=/rest/fc-sans/device-managers/a283d916-8dfd-46a0-a264-a06fa0aaed03/unimported-sans}
VERBOSE: [REMOVE-HPOVRESOURCE] Querying appliance index for resource.
VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters:
 
Key   : uri
Value : /rest/index/resources?filter=name='@{uri=/rest/fc-sans/device-managers/a283d916-8dfd-46a0-a264-a06fa0aaed03;
        name=172.28.10.37; type=FCDeviceManagerV2; state=Ready; status=OK; category=fc-device-managers;
        connectionInfo=System.Object[]; created=2015-12-02T22:38:53.792Z; description=Brocade Network Advisor;
        deviceManagerUrl=https://172.28.10.37:443/dcm-client/dcmclient.jnlp?module=Main;
        deviceManagerVersion=12.4.1.23; eTag=60a93713-908f-4d96-b168-99fbbae98f9e; isInternal=False;
        managedSansUri=/rest/fc-sans/device-managers/a283d916-8dfd-46a0-a264-a06fa0aaed03/managed-sans;
        modified=2015-12-04T22:28:15.008Z; providerDisplayName=Brocade Network Advisor;
        providerUri=/rest/fc-sans/providers/0aa1f4e1-3b5e-4233-af1a-f849dc64da69; refreshState=Stable;
        unimportedSansUri=/rest/fc-sans/device-managers/a283d916-8dfd-46a0-a264-a06fa0aaed03/unimported-sans}'
 
 
 
VERBOSE: [SEND-HPOVREQUEST] SSLCheckFlag: True
VERBOSE: [SEND-HPOVREQUEST] Requested URI:
/rest/index/resources?filter=name='@{uri=/rest/fc-sans/device-managers/a283d916-8dfd-46a0-a264-a06fa0aaed03;
name=172.28.10.37; type=FCDeviceManagerV2; state=Ready; status=OK; category=fc-device-managers;
connectionInfo=System.Object[]; created=2015-12-02T22:38:53.792Z; description=Brocade Network Advisor;
deviceManagerUrl=https://172.28.10.37:443/dcm-client/dcmclient.jnlp?module=Main; deviceManagerVersion=12.4.1.23;
eTag=60a93713-908f-4d96-b168-99fbbae98f9e; isInternal=False;
managedSansUri=/rest/fc-sans/device-managers/a283d916-8dfd-46a0-a264-a06fa0aaed03/managed-sans;
modified=2015-12-04T22:28:15.008Z; providerDisplayName=Brocade Network Advisor;
providerUri=/rest/fc-sans/providers/0aa1f4e1-3b5e-4233-af1a-f849dc64da69; refreshState=Stable;
unimportedSansUri=/rest/fc-sans/device-managers/a283d916-8dfd-46a0-a264-a06fa0aaed03/unimported-sans}'
VERBOSE: [SEND-HPOVREQUEST] PROCESS
VERBOSE: [RESTCLIENT] Bound PS Parameters:
Key    Value
 
---    -----
 
method GET
 
uri    /rest/index/resources?filter=name='@{uri=/rest/fc-sans/device-managers/a283d916-8dfd-46a0-a264-a06fa0aaed03;
 
       name=172.28.10.37; type=FCDeviceManagerV2; state=Ready; status=OK; category=fc-device-managers;
 
       connectionInfo=System.Object[]; created=2015-12-02T22:38:53.792Z; description=Brocade Network Advisor;
 
       deviceManagerUrl=https://172.28.10.37:443/dcm-client/dcmclient.jnlp?module=Main;
 
       deviceManagerVersion=12.4.1.23; eTag=60a93713-908f-4d96-b168-99fbbae98f9e; isInternal=False;
 
       managedSansUri=/rest/fc-sans/device-managers/a283d916-8dfd-46a0-a264-a06fa0aaed03/managed-sans;
 
       modified=2015-12-04T22:28:15.008Z; providerDisplayName=Brocade Network Advisor;
 
       providerUri=/rest/fc-sans/providers/0aa1f4e1-3b5e-4233-af1a-f849dc64da69; refreshState=Stable;
 
       unimportedSansUri=/rest/fc-sans/device-managers/a283d916-8dfd-46a0-a264-a06fa0aaed03/unimported-sans}'
 
 
 
VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for GET
https://172.28.10.1/rest/index/resources?filter=name='@{uri=/rest/fc-sans/device-managers/a283d916-8dfd-46a0-a264-a06fa
0aaed03; name=172.28.10.37; type=FCDeviceManagerV2; state=Ready; status=OK; category=fc-device-managers;
connectionInfo=System.Object[]; created=2015-12-02T22:38:53.792Z; description=Brocade Network Advisor;
deviceManagerUrl=https://172.28.10.37:443/dcm-client/dcmclient.jnlp?module=Main; deviceManagerVersion=12.4.1.23;
eTag=60a93713-908f-4d96-b168-99fbbae98f9e; isInternal=False;
managedSansUri=/rest/fc-sans/device-managers/a283d916-8dfd-46a0-a264-a06fa0aaed03/managed-sans;
modified=2015-12-04T22:28:15.008Z; providerDisplayName=Brocade Network Advisor;
providerUri=/rest/fc-sans/providers/0aa1f4e1-3b5e-4233-af1a-f849dc64da69; refreshState=Stable;
unimportedSansUri=/rest/fc-sans/device-managers/a283d916-8dfd-46a0-a264-a06fa0aaed03/unimported-sans}'
VERBOSE: [SEND-HPOVREQUEST] Request: GET
https://172.28.10.1/rest/index/resources?filter=name='@{uri=/rest/fc-sans/device-managers/a283d916-8dfd-46a0-a264-a06fa
0aaed03; name=172.28.10.37; type=FCDeviceManagerV2; state=Ready; status=OK; category=fc-device-managers;
connectionInfo=System.Object[]; created=2015-12-02T22:38:53.792Z; description=Brocade Network Advisor;
deviceManagerUrl=https://172.28.10.37:443/dcm-client/dcmclient.jnlp?module=Main; deviceManagerVersion=12.4.1.23;
eTag=60a93713-908f-4d96-b168-99fbbae98f9e; isInternal=False;
managedSansUri=/rest/fc-sans/device-managers/a283d916-8dfd-46a0-a264-a06fa0aaed03/managed-sans;
modified=2015-12-04T22:28:15.008Z; providerDisplayName=Brocade Network Advisor;
providerUri=/rest/fc-sans/providers/0aa1f4e1-3b5e-4233-af1a-f849dc64da69; refreshState=Stable;
unimportedSansUri=/rest/fc-sans/device-managers/a283d916-8dfd-46a0-a264-a06fa0aaed03/unimported-sans}'
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Accept = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: X-API-Version = 120
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: auth = o5dhMmFdm6IOxZBsrMo6HuWMXM5AYWVT
VERBOSE: [SEND-HPOVREQUEST] Response Status: 200 OK
VERBOSE: [SEND-HPOVREQUEST] Response Header 1: Vary = Accept-Encoding
VERBOSE: [SEND-HPOVREQUEST] Response Header 2: Content-Encoding =
VERBOSE: [SEND-HPOVREQUEST] Response Header 3: Transfer-Encoding = chunked
VERBOSE: [SEND-HPOVREQUEST] Response Header 4: Cache-Control = no-cache
VERBOSE: [SEND-HPOVREQUEST] Response Header 5: Content-Type = application/json;charset=UTF-8
VERBOSE: [SEND-HPOVREQUEST] Response Header 6: Date = Fri, 04 Dec 2015 22:33:23 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header 7: Via = 1.1 hponeview.customer1.host.local
VERBOSE: [SEND-HPOVREQUEST] Response:
 
type            : IndexPaginatedCollectionV4
start           : 0
count           : 0
total           : 0
unFilteredTotal : 21287
uri             :
/rest/index/resources?count=50&start=0&filter=name%3D'@%7Buri%3D/rest/fc-sans/device-managers/a283d91
 
6-8dfd-46a0-a264-a06fa0aaed03;%20name%3D172.28.10.37;%20type%3DFCDeviceManagerV2;%20state%3DReady;%20
 
status%3DOK;%20category%3Dfc-device-managers;%20connectionInfo%3DSystem.Object%5B%5D;%20created%3D201
 
5-12-02T22:38:53.792Z;%20description%3DBrocade%20Network%20Advisor;%20deviceManagerUrl%3Dhttps://172.
 
28.10.37:443/dcm-client/dcmclient.jnlp?module%3DMain;%20deviceManagerVersion%3D12.4.1.23;%20eTag%3D60
 
a93713-908f-4d96-b168-99fbbae98f9e;%20isInternal%3DFalse;%20managedSansUri%3D/rest/fc-sans/device-man
 
agers/a283d916-8dfd-46a0-a264-a06fa0aaed03/managed-sans;%20modified%3D2015-12-04T22:28:15.008Z;%20pro
 
viderDisplayName%3DBrocade%20Network%20Advisor;%20providerUri%3D/rest/fc-sans/providers/0aa1f4e1-3b5e
 
-4233-af1a-f849dc64da69;%20refreshState%3DStable;%20unimportedSansUri%3D/rest/fc-sans/device-managers
                  /a283d916-8dfd-46a0-a264-a06fa0aaed03/unimported-sans%7D'
category        : resources
members         : {}
prevPageUri     :
nextPageUri     :
created         :
modified        :
eTag            :
 
 
 
VERBOSE: [SEND-HPOVREQUEST] Manual Pagination: False
VERBOSE: [SEND-HPOVREQUEST] END
VERBOSE: [REMOVE-HPOVRESOURCE] Found 0 resources.
VERBOSE: [NEW-ERRORRECORD] Building ErrorRecord object
Remove-HPOVResource : Resource '@{uri=/rest/fc-sans/device-managers/a283d916-8dfd-46a0-a264-a06fa0aaed03;
name=172.28.10.37; type=FCDeviceManagerV2; state=Ready; status=OK; category=fc-device-managers;
connectionInfo=System.Object[]; created=2015-12-02T22:38:53.792Z; description=Brocade Network Advisor;
deviceManagerUrl=https://172.28.10.37:443/dcm-client/dcmclient.jnlp?module=Main; deviceManagerVersion=12.4.1.23;
eTag=60a93713-908f-4d96-b168-99fbbae98f9e; isInternal=False;
managedSansUri=/rest/fc-sans/device-managers/a283d916-8dfd-46a0-a264-a06fa0aaed03/managed-sans;
modified=2015-12-04T22:28:15.008Z; providerDisplayName=Brocade Network Advisor;
providerUri=/rest/fc-sans/providers/0aa1f4e1-3b5e-4233-af1a-f849dc64da69; refreshState=Stable;
unimportedSansUri=/rest/fc-sans/device-managers/a283d916-8dfd-46a0-a264-a06fa0aaed03/unimported-sans}' not found.
Please check the resource value provided and try the call again.
At C:\Users\HPCSAdmin\Documents\WindowsPowerShell\Modules\HPOneView.120\HPOneView.120.psm1:11960 char:32
+                         else { Remove-HPOVResource -nameOrUri $manager }
+                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (nameOrUri:String) [Remove-HPOVResource], InvalidOperationException
    + FullyQualifiedErrorId : ResourceNotFound,Remove-HPOVResource

**Comment by ChrisLynchHP** [comment] 2015-12-07 19:29
Ah, I see.  Looks like we are passing the object into a helper cmdlet that is being converted to a String value, when we should have been passing the objects URI. As a work around, use the –Force switch when calling Remove-HPOVSanManager.

**Comment by ChrisLynchHP** [comment] 2015-12-15 19:37
This is fixed in the a99a9b65d769ff1b737542da5cc29839d6baf3d8 (Release 1.20.275.0) release.  Closing.

**Closed by ChrisLynchHP** 2015-12-15 19:37 UTC
Labels: bug
