### ISSUE TITLE
OneView backup is empty - backup file 0 KB

### ISSUE THREAD

**Issue by valfr** [HewlettPackard/POSH-HPOneView#169] opened 2016-08-25 08:59 UTC
When creating a backup with a the command "new-HPOVbackup -Location C:\", file is created but empty 0 KB.

### Expected Behavior
Obtain a backup file

### Actual Behavior
Empty and unusable backup file

### Steps to reproduce
Installing last POSH Library Release 2.0.620.0 
Import-Module HPOneView.200
Connect-HPOVMgmt
new-HPOVbackup -Location C:\

### Resolved by
Installing last POSH Library Release 2.0.430.0 (May 24)

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): Release 2.0.620.0 
HPE OneView Appliance Version:  2.00.02
Output from `$PSVersionTable` on your Windows Host:
Name  : PSVersion
Value : 4.0

Name  : WSManStackVersion
Value : 3.0

Name  : SerializationVersion
Value : 1.1.0.1

Name  : CLRVersion
Value : 4.0.30319.34014

Name  : BuildVersion
Value : 6.3.9600.17400

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0}

Name  : PSRemotingProtocolVersion
Value : 2.2

**Comment by ChrisLynchHPE** [comment] 2016-08-25 15:51
Confirmed bug.  Not sure why this is happening yet.  Still investigating.

**Comment by ChrisLynchHPE** [comment] 2016-08-25 16:01
Found the and fixed the issue.  Any Cmdlet that attempts to download a file (`New-HPOVBackup`, `New-HPOVSupportDump`, `Show-HPOVPortStatistics`) will not download the file correctly due to an error in an internal helper function.  I will release a small rev release that addresses this issue today.

**Comment by erikgraa** [comment] 2016-08-28 19:07
Is Get-HPOVAuditLog affected?

**Comment by ChrisLynchHPE** [comment] 2016-08-29 03:30
Yes.  This is now fixed in the [Release 2.0.621.0] (https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.621.0).

**Closed** 2016-08-29 03:31 UTC
Labels: Appliance Backup/Restore, Bug, Impact - High
