### ISSUE TITLE
Get-HPOVAlert fails when running in a scheduled task

### ISSUE THREAD

**Issue by alfredocolon** [HewlettPackard/POSH-HPOneView#507] opened 2020-09-29 00:53 UTC
I have an odd problem with a POSH script that I use to grab the alerts from HPOV, write them to a CSV file, which will later get ingested by Splunk.

If I run the PowerShell script manually, everything works OK and the alerts are retrieved from the appliance.  However, when the script is run as a scheduled task, the call to Get-HPOVAlert in particular seems to fail (it returns 0 alerts).

Is there a limitation when running as a scheduled task?  The code is pretty straightforward, the relevant portion is shown below:

```
Log("Calling Get-HPOVServer...")
$servers = Get-HPOVServer    # get the known list of servers    ### This works OK

Log("Getting all alerts for the past $tWindow days...")
$alerts = Get-HPOVAlert     -TimeSpan (New-TimeSpan -Days $tWindow)  ### This does not
                             # get all alerts for the past $tWindow units

Log("Processing " + $alerts.Count + " alerts...")     ### Returns 0 as a task, non-zero when run interactively
```

**Comment by alfredocolon** [comment] 2020-09-29 13:57
Here's the complete script, with sensitive data redacted.

```
# Function to return the current date & time stamp
#
Function Get-TimeStamp {
    
    return "[{0:MM/dd/yy} {0:HH:mm:ss}]" -f (Get-Date)   
}


# Function to prepend the current date & time to the incoming message
Function Log {
  param (
    [string]$message
  )

  $outputLog = "D:\Commands\PS_History.txt"

  "$(Get-TimeStamp) $message" | Out-File $outputLog -Append
}

# Setup and initialization
#
$StartTime = $(get-date)

$OVhost = "<SERVERNAME>"
$tWindow = 7   # default number of days alert history

# Close any existing connections
#
Log("Starting... Calling Disconnect-HPOVMgmt")
Disconnect-HPOVMgmt -ea SilentlyContinue

# Get ready to connect to the appliance (the password is stored in an encrypted file)
#
$username = "Admin"
$password = Get-Content 'D:\Commands\mysecurestring-ADMIN.txt' | ConvertTo-SecureString
# $cred = new-object -typename System.Management.Automation.PSCredential  -argumentlist $username, $password

Log("Calling Connect-HPOVMgmt")
# Connect-HPOVMgmt -Hostname $OVhost -Credential $cred -LoginAcknowledge
Connect-HPOVMgmt -Hostname $OVhost -UserName $username -Password $password -AuthLoginDomain LOCAL -LoginAcknowledge

if ($ConnectedSessions -eq $null) {
  Log("Error!  Connection to $OVhost not established")
  break;
}

$fileName = "D:\Commands\HPOVtoSplunk.csv"
# $fileName = "D:\Commands\HPOVtoSplunk-$(((get-date).ToUniversalTime()).ToString("yyyyMMddTHHmmssZ")).csv"

Log("Calling Get-HPOVServer...")
$servers = Get-HPOVServer    # get the known list of servers

Log("Getting all alerts for the past $tWindow days...")
$alerts = Get-HPOVAlert -TimeSpan (New-TimeSpan -Days $tWindow)
                             # get all alerts for the past $tWindow units

Log("Processing " + $alerts.Count + " alerts...")
$arrayResults = @()

foreach ($a in $alerts) { 
  $severity = $a.severity;
  $created = $a.created;
  $desc = $a.description;
  $clearedTime = $a.clearedTime;
  $urgency = $a.urgency;
  $healthCategory = $a.healthCategory;

  $resource = $a.associatedResource.resourceName;
  foreach ($seek in $servers) { 
    if ($seek.name -eq $resource) { 
         $theServer = $seek.servername;
         # Log("$theServer was found")
         break;
    }
  }

  $objItemDetails = [PSCustomObject]@{         # create an object that we'll add to an array, for subsequent output to a CSV file
    ClearedTime = $clearedTime;
    Urgency = $urgency;
    HealthCategory = $healthCategory;
    Severity = $severity;
    Created = $created;
    Description = $desc;
    ResourceName = $resource;
    ServerName = $theServer;
  }

  $arrayResults += $objItemDetails
}

Log("Exporting the results to $filename")
$arrayResults | Export-Csv $fileName -NoTypeInformation -Force

Log("Disconnecting from the appliance: $OVhost")
Disconnect-HPOVMgmt

Log("Processing has completed.  Results written to $filename")
$elapsedTime = $(get-date) - $StartTime

$totalTime = "{0:HH:mm:ss}" -f ([datetime]$elapsedTime.Ticks)
Log("Elasped time: $totalTime")

Log("===============")
```

**Comment by ChrisLynchHPE** [comment] 2020-09-29 14:30
From what I can see, this is caused by an issue with how the Cmdlet handles time objects provided.   I was able to fix this in a 5.00 update I have in the process of being published.  An update to the 5.20, 5.30 and 5.40 libraries.  

But any of the Cmdlets can be used in a non-interactive script.

**Comment by alfredocolon** [comment] 2020-09-29 15:43
Thanks Chris.  I look forward to your updates.

**Comment by alfredocolon** [comment] 2020-09-29 20:28
Chris, I've done more testing on this, and found out that your code doesn't seem to be at fault.  I set up the Windows task to run under my domain admin account vs. a service account, and the script ran fine (we maintain separate accounts for 'regular' day-to-day stuff, vs. admin stuff on our servers).  My server admin account must have some special permission that isn't granted to the service account.  Both accounts are part of the Administrators group, although I note that I cannot RDP into the server using the service account.

I am, however, curious as to what the cmdlet is doing that would conflict with the account that the process is running under, vs. the account I'm using to create a session with the appliance.  If you can shed some light on that, it might help me figure out which permissions are missing.  Perhaps a Group Policy setting?  Thanks again.

**Comment by ChrisLynchHPE** [comment] 2020-09-29 23:42
The library has no requirements for any special permissions.  Although, the files must be trusted and unblocked for them to load properly.  But if you have two user accounts with identical permissions and the library is installed for all users (under `$env:ProgramFiles\WindowsPowerShell\Modules`), then either account should be able to import the module and use the Cmdlets.

**Comment by ChrisLynchHPE** [comment] 2021-02-09 22:58
This is now addressed in the following releases:

* [5.50.2680.1687](https://www.powershellgallery.com/packages/HPEOneView.550/5.50.2680.1687) 
* [5.40.2681.1725](https://www.powershellgallery.com/packages/HPEOneView.540/5.40.2681.1725)
* [5.30.2682.3811](https://www.powershellgallery.com/packages/HPEOneView.530/5.30.2682.3811)
* [5.20.2684.2161](https://www.powershellgallery.com/packages/HPOneView.520/5.20.2684.2161)
* [5.00.2685.1865](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2685.1865)

Please verify prior to closing this issue.

**Comment by ChrisLynchHPE** [comment] 2022-07-19 18:51
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.

**Closed as completed by ChrisLynchHPE** 2022-07-19 18:51 UTC
Labels: Bug, Impact - Medium, Alerting, PendingVerification, 5.00, 5.20, 5.30, 5.40
