### ISSUE TITLE
New-HPOVServerProfileTemplate and -FirmwareMode parameter

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#191] opened 2016-12-19 20:43 UTC
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
The help of New-HPOVServerProfileTemplate  provides the following details for FirmwareMode:
    -FirmwareMode <String>
        Define the mode a firmware baseline will be deployed.  Allowed value:
        
        * FirmwareOnly - Updates the firmware without powering down the server hardware using using HP Smart Update Tools. 
        * FirmwareAndSoftware - Updates the firmware and OS drivers without powering down the server hardware using HP Smart Update Tools.  
        * FirmwareOffline - Manages the firmware through HP OneView. Selecting this option requires the server hardware to be powered down.

However when looking at the attribute for a SPT object, the value is FirmwareAndOSDrivers instead of FirmwareAndSoftware  

Please update the library and help accordingly

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.0.1170.1173
HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:

**Comment by ChrisLynchHPE** [comment] 2016-12-19 21:03
This is by design to follow the UI.

**Comment by DungKHoang** [comment] 2016-12-20 00:20
The UI does say Firmware and OS drivers
![fw](https://cloud.githubusercontent.com/assets/9196456/21333744/0637de56-c607-11e6-8943-d55897944ea9.PNG)

**Comment by ChrisLynchHPE** [comment] 2017-01-05 00:34
The parameter value isn't going to change, as this has been the option since 2.00.  Closing.

**Closed by ChrisLynchHPE** 2017-01-05 00:34 UTC
Labels: Question
