### ISSUE TITLE
Get-OVAlert -Start  -End  

### ISSUE THREAD

**Issue by GitHubManigr** [HewlettPackard/POSH-HPOneView#605] opened 2022-04-04 15:35 UTC
we discovered an issue with the command **Get-OVAlert** -Start "2022-01-01" -End "2022-04-04", this should according to the documentation return all alerts starting at 2012-**01-01** to 2022-**04-04**  
( "Example 9" at https://hpe-docs.gitbook.io/posh-hpeoneview/cmdlets/v5.50/appliance/get-ovalert ).

BUT the result is:  ( empty ) 

Command:  	Get-OVAlert -Start "2022-**01-01**" -End "2022-**04-04**"
Result:		“  “

Changing now the date to ( actually going backwards ) 

Command:     Get-OVAlert -Start "2022-**04-04**" -End "2022-**01-01**"
Result:

                       Result:		Severity Resource                         Created                  Modified                 State   AssignedToUser Description               
-------- --------                         -------                  --------                 -----   -------------- -----------               
OK       rkaushana121rb                   Mo. Apr  4 01:53:10 2022 Mo. Apr  4 01:53:10 2022 Cleared                Storage - Controller Sl...
OK       rkaushana121rb                   Mo. Apr  4 01:52:38 2022 Mo. Apr  4 01:52:38 2022 Cleared                Storage - Controller Sl...
OK       rkaushana109rb                   So. Apr  3 23:16:49 2022 So. Apr  3 23:16:49 2022 Cleared                Storage - Controller Sl...
OK       rkaushana109rb                   So. Apr  3 23:15:30 2022 So. Apr  3 23:15:30 2022 Cleared                Storage - Controller Sl...
OK       rkaushana118rb                   So. Apr  3 20:57:36 2022 So. Apr  3 20:57:36 2022 Cleared                Storage - Controller Sl...
OK       rkaushana118rb                   So. Apr  3 20:55:46 2022 So. Apr  3 20:55:46 2022 Cleared                Storage - Controller Sl...

... this is what my customer is looking to get resolved.

Ralf

**Comment by ChrisLynchHPE** [comment] 2022-06-22 01:19
I'm not able to reproduce this behavior.  `-Start` is closest to now.  `-End` is how far back you want to filter for.

```powershell
[PS] C:\Users\chris> Get-OVAlert -Start "2022-06-21" -End "2022-06-08" -OutVariable alerts

Severity Resource                                    Created                  Modified                 State   Assigned
                                                                                                               ToUser
-------- --------                                    -------                  --------                 -----   --------
Critical 10.152.50.89                                Sat 18 Jun 2022 01:44:13 Sat 18 Jun 2022 02:48:57 Cleared
Critical 10.152.50.89                                Fri 17 Jun 2022 06:14:13 Fri 17 Jun 2022 07:18:57 Cleared
OK       3-CN75160607, bay 2                         Fri 17 Jun 2022 06:13:13 Fri 17 Jun 2022 06:13:13 Cleared
Critical 3-CN75160607, bay 2                         Fri 17 Jun 2022 06:13:12 Fri 17 Jun 2022 06:13:13 Cleared
OK       1-CN750160YK, bay 1                         Thu 16 Jun 2022 21:17:43 Thu 16 Jun 2022 21:17:43 Cleared
Critical 1-CN750160YK, bay 1                         Thu 16 Jun 2022 21:17:41 Thu 16 Jun 2022 21:17:43 Cleared
Critical zpo3par-7200-1-srv                          Thu 16 Jun 2022 21:15:16 Thu 16 Jun 2022 21:34:36 Cleared
Critical 10.152.50.89                                Thu 16 Jun 2022 20:29:13 Thu 16 Jun 2022 21:33:57 Cleared
Warning  Remote Support                              Wed 15 Jun 2022 07:06:00 Wed 15 Jun 2022 07:06:00 Active
Critical zpo3par-7200-1-srv                          Sat 11 Jun 2022 05:35:16 Sat 11 Jun 2022 05:54:36 Cleared
Critical 10.152.50.89                                Fri 10 Jun 2022 03:04:13 Fri 10 Jun 2022 04:08:57 Cleared
Critical Gen9 custom 2018 07 10                      Thu 09 Jun 2022 17:04:01 Thu 09 Jun 2022 17:04:01 Locked
Critical Custom Gen10 NOV MSB SPP b38 OVG 2018 11 16 Thu 09 Jun 2022 17:04:00 Thu 09 Jun 2022 17:04:00 Locked
Critical RHEL 7.3 660b                               Thu 09 Jun 2022 17:04:00 Thu 09 Jun 2022 17:04:00 Locked
Warning  No SPT, 620, simple - centos                Thu 09 Jun 2022 17:03:59 Thu 09 Jun 2022 17:03:59 Active
Warning  demofestrhel5                               Thu 09 Jun 2022 17:03:59 Thu 09 Jun 2022 17:03:59 Active
Critical CentOS 7                                    Thu 09 Jun 2022 17:03:59 Thu 09 Jun 2022 17:03:59 Locked
Warning  edgar-bd2                                   Thu 09 Jun 2022 17:03:59 Thu 09 Jun 2022 17:03:59 Active
Warning  620 fw update to latest                     Thu 09 Jun 2022 17:03:59 Thu 09 Jun 2022 17:03:59 Active
Critical RHEL 7.3 660                                Thu 09 Jun 2022 17:03:58 Thu 09 Jun 2022 17:03:58 Locked
Warning  demofestrhel4                               Thu 09 Jun 2022 17:03:58 Thu 09 Jun 2022 17:03:58 Active
Warning  edgar-bd3                                   Thu 09 Jun 2022 17:03:58 Thu 09 Jun 2022 17:03:58 Active
Warning  demofestrhel                                Thu 09 Jun 2022 17:03:57 Thu 09 Jun 2022 17:03:57 Active
Warning  edgar-bd1                                   Thu 09 Jun 2022 17:03:57 Thu 09 Jun 2022 17:03:57 Active
Critical RHEL 7.3                                    Thu 09 Jun 2022 17:03:57 Thu 09 Jun 2022 17:03:57 Locked
Warning  HPE Synergy Service Pack                    Thu 09 Jun 2022 17:03:57 Thu 09 Jun 2022 17:03:57 Locked
Critical HPE Synergy Service Pack                    Thu 09 Jun 2022 17:03:57 Thu 09 Jun 2022 17:03:57 Locked
Critical HPE Synergy Service Pack                    Thu 09 Jun 2022 17:03:57 Thu 09 Jun 2022 17:03:57 Locked
Critical Gen9 Service Pack for ProLiant              Thu 09 Jun 2022 17:03:56 Thu 09 Jun 2022 17:03:56 Locked
Critical Gen10 Service Pack for ProLiant             Thu 09 Jun 2022 17:03:55 Thu 09 Jun 2022 17:03:55 Locked
Critical remote                                      Thu 09 Jun 2022 17:03:55 Thu 09 Jun 2022 17:03:55 Active
Warning  HPE Synergy Service Pack                    Thu 09 Jun 2022 16:30:07 Thu 09 Jun 2022 16:30:07 Cleared
Warning  HPE Synergy Service Pack                    Thu 09 Jun 2022 16:30:07 Thu 09 Jun 2022 16:30:07 Cleared
Warning  HPE Synergy Service Pack                    Thu 09 Jun 2022 16:30:07 Thu 09 Jun 2022 16:30:07 Cleared
Warning  Remote Support                              Wed 08 Jun 2022 07:06:00 Wed 15 Jun 2022 07:06:00 Cleared

[PS] C:\Users\chris> $alerts.Count
35

# The following will return 50 alerts (there are many more alerts than 50 on this appliance
[PS] C:\Users\chris> Get-OVAlert -Count 50

Severity Resource                                    Created                  Modified                 State   Assigned
                                                                                                               ToUser
-------- --------                                    -------                  --------                 -----   --------
Critical 10.152.50.89                                Sat 18 Jun 2022 01:44:13 Sat 18 Jun 2022 02:48:57 Cleared
Critical 10.152.50.89                                Fri 17 Jun 2022 06:14:13 Fri 17 Jun 2022 07:18:57 Cleared
OK       3-CN75160607, bay 2                         Fri 17 Jun 2022 06:13:13 Fri 17 Jun 2022 06:13:13 Cleared
Critical 3-CN75160607, bay 2                         Fri 17 Jun 2022 06:13:12 Fri 17 Jun 2022 06:13:13 Cleared
OK       1-CN750160YK, bay 1                         Thu 16 Jun 2022 21:17:43 Thu 16 Jun 2022 21:17:43 Cleared
Critical 1-CN750160YK, bay 1                         Thu 16 Jun 2022 21:17:41 Thu 16 Jun 2022 21:17:43 Cleared
Critical zpo3par-7200-1-srv                          Thu 16 Jun 2022 21:15:16 Thu 16 Jun 2022 21:34:36 Cleared
Critical 10.152.50.89                                Thu 16 Jun 2022 20:29:13 Thu 16 Jun 2022 21:33:57 Cleared
Warning  Remote Support                              Wed 15 Jun 2022 07:06:00 Wed 15 Jun 2022 07:06:00 Active
Critical zpo3par-7200-1-srv                          Sat 11 Jun 2022 05:35:16 Sat 11 Jun 2022 05:54:36 Cleared
Critical 10.152.50.89                                Fri 10 Jun 2022 03:04:13 Fri 10 Jun 2022 04:08:57 Cleared
Critical Gen9 custom 2018 07 10                      Thu 09 Jun 2022 17:04:01 Thu 09 Jun 2022 17:04:01 Locked
Critical Custom Gen10 NOV MSB SPP b38 OVG 2018 11 16 Thu 09 Jun 2022 17:04:00 Thu 09 Jun 2022 17:04:00 Locked
Critical RHEL 7.3 660b                               Thu 09 Jun 2022 17:04:00 Thu 09 Jun 2022 17:04:00 Locked
Warning  No SPT, 620, simple - centos                Thu 09 Jun 2022 17:03:59 Thu 09 Jun 2022 17:03:59 Active
Warning  demofestrhel5                               Thu 09 Jun 2022 17:03:59 Thu 09 Jun 2022 17:03:59 Active
Critical CentOS 7                                    Thu 09 Jun 2022 17:03:59 Thu 09 Jun 2022 17:03:59 Locked
Warning  edgar-bd2                                   Thu 09 Jun 2022 17:03:59 Thu 09 Jun 2022 17:03:59 Active
Warning  620 fw update to latest                     Thu 09 Jun 2022 17:03:59 Thu 09 Jun 2022 17:03:59 Active
Critical RHEL 7.3 660                                Thu 09 Jun 2022 17:03:58 Thu 09 Jun 2022 17:03:58 Locked
Warning  demofestrhel4                               Thu 09 Jun 2022 17:03:58 Thu 09 Jun 2022 17:03:58 Active
Warning  edgar-bd3                                   Thu 09 Jun 2022 17:03:58 Thu 09 Jun 2022 17:03:58 Active
Warning  demofestrhel                                Thu 09 Jun 2022 17:03:57 Thu 09 Jun 2022 17:03:57 Active
Warning  edgar-bd1                                   Thu 09 Jun 2022 17:03:57 Thu 09 Jun 2022 17:03:57 Active
Critical RHEL 7.3                                    Thu 09 Jun 2022 17:03:57 Thu 09 Jun 2022 17:03:57 Locked
Warning  HPE Synergy Service Pack                    Thu 09 Jun 2022 17:03:57 Thu 09 Jun 2022 17:03:57 Locked
Critical HPE Synergy Service Pack                    Thu 09 Jun 2022 17:03:57 Thu 09 Jun 2022 17:03:57 Locked
Critical HPE Synergy Service Pack                    Thu 09 Jun 2022 17:03:57 Thu 09 Jun 2022 17:03:57 Locked
Critical Gen9 Service Pack for ProLiant              Thu 09 Jun 2022 17:03:56 Thu 09 Jun 2022 17:03:56 Locked
Critical Gen10 Service Pack for ProLiant             Thu 09 Jun 2022 17:03:55 Thu 09 Jun 2022 17:03:55 Locked
Critical remote                                      Thu 09 Jun 2022 17:03:55 Thu 09 Jun 2022 17:03:55 Active
Warning  HPE Synergy Service Pack                    Thu 09 Jun 2022 16:30:07 Thu 09 Jun 2022 16:30:07 Cleared
Warning  HPE Synergy Service Pack                    Thu 09 Jun 2022 16:30:07 Thu 09 Jun 2022 16:30:07 Cleared
Warning  HPE Synergy Service Pack                    Thu 09 Jun 2022 16:30:07 Thu 09 Jun 2022 16:30:07 Cleared
Warning  Remote Support                              Wed 08 Jun 2022 07:06:00 Wed 15 Jun 2022 07:06:00 Cleared
OK       Gen9 custom 2018 07 10                      Sun 05 Jun 2022 18:22:49 Sun 05 Jun 2022 18:22:49 Cleared
OK       Custom Gen10 NOV MSB SPP b38 OVG 2018 11 16 Sun 05 Jun 2022 18:22:48 Sun 05 Jun 2022 18:22:48 Cleared
OK       HPE Synergy Service Pack                    Sun 05 Jun 2022 18:22:47 Sun 05 Jun 2022 18:22:47 Cleared
OK       HPE Synergy Service Pack                    Sun 05 Jun 2022 18:22:46 Sun 05 Jun 2022 18:22:46 Cleared
OK       HPE Synergy Service Pack                    Sun 05 Jun 2022 18:22:46 Sun 05 Jun 2022 18:22:46 Cleared
OK       Gen9 Service Pack for ProLiant              Sun 05 Jun 2022 18:22:45 Sun 05 Jun 2022 18:22:45 Cleared
OK       Gen10 Service Pack for ProLiant             Sun 05 Jun 2022 18:22:44 Sun 05 Jun 2022 18:22:44 Cleared
OK       remote                                      Sun 05 Jun 2022 18:22:44 Sun 05 Jun 2022 18:22:44 Cleared
Critical Gen9 custom 2018 07 10                      Sun 05 Jun 2022 18:18:08 Sun 05 Jun 2022 18:22:49 Cleared
Critical Custom Gen10 NOV MSB SPP b38 OVG 2018 11 16 Sun 05 Jun 2022 18:18:08 Sun 05 Jun 2022 18:22:48 Cleared
Critical RHEL 7.3 660b                               Sun 05 Jun 2022 18:18:07 Sun 05 Jun 2022 18:22:48 Cleared
Warning  No SPT, 620, simple - centos                Sun 05 Jun 2022 18:18:07 Sun 05 Jun 2022 18:22:48 Cleared
Critical CentOS 7                                    Sun 05 Jun 2022 18:18:07 Sun 05 Jun 2022 18:22:47 Cleared
Warning  demofestrhel5                               Sun 05 Jun 2022 18:18:07 Sun 05 Jun 2022 18:22:48 Cleared
Warning  edgar-bd2                                   Sun 05 Jun 2022 18:18:07 Sun 05 Jun 2022 18:22:47 Cleared
```

**Comment by ChrisLynchHPE** [comment] 2022-11-18 21:01
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.

**Closed as completed by ChrisLynchHPE** 2022-11-18 21:01 UTC
Labels: NeedMoreInformation
