### ISSUE TITLE
new-HPOVlicense issue?

### ISSUE THREAD

**Issue by tknightblc** [HewlettPackard/POSH-HPOneView#57] opened 2016-01-21 18:22 UTC
Trying to add license with new POSH 2.xx library - nothing happens, I got no error response and license did not get added. I can manually add same license without issue and this works in 1.20 library without ApplianceConnection:

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> write $Connection1

ConnectionID Name                          UserName      AuthLoginDomain
------------ ----                          --------      ---------------
1            tk1-ov200-dcsdemo.advizex.net Administrator LOCAL          

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $License1 = '9CTA C9MA H9PA 8HV2 V7B5 HWWB Y9JL KMPL 4HVC ND5M DXAU 2CSM GHTG L762 U9SZ XWJA KJVT D5KM EFVW DT5J 53L9 4QWC AK2P 3EW2 9KQM HUZZ TZZX 9B5X 82Z5 WHEF GE4C LUE3 BKT8 WXDG NK6Y C4GA HZL4 XBE7 3VJ6 2MSU 4ZU9 9WGG CZU7 WE4X YN44 CH55 KZLG 2F4N A8RJ UKEC 3F9V JQY5 "423373011 HPOV-NFR1 HP_OneView_16_Seat_NFR 26AYJUDH7YYC"_3Q29P-45PV3-YGD7P-KC3G4-WXSXR'

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> new-HPOVlicense $License1 -ApplianceConnection $Connection1

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy>

**Comment by ChrisLynchHP** [comment] 2016-01-21 18:52
This is a duplicate of #55 .

**Closed by ChrisLynchHP** 2016-01-21 18:52 UTC
Labels: duplicate
