### ISSUE TITLE
Error with Add-OVBaseline

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#666] opened 2023-12-04 17:54 UTC
### Expected Behavior
Add SPP to Synergy OneView firmware bundle

### Actual Behavior
Error with cmdlet

### Steps to reproduce
Add-OVBaseline -file SPP.....

```

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`): 8.50
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  8.6
Output from `$PSVersionTable` on your Windows Host:7.3.5
```

[2312030711_HPEOV_transcript.log](https://github.com/HewlettPackard/POSH-HPEOneView/files/13549703/2312030711_HPEOV_transcript.log)

**Comment by ChrisLynchHPE** [comment] 2024-10-02 04:16
This is a duplicate of #427 .  I have added a workaround to the noted libraries in the original report.  Closing.

**Closed as completed by ChrisLynchHPE** 2024-10-02 04:16 UTC
Labels: Bug, NeedMoreInformation
