### ISSUE TITLE
The "-WhatIf" parameter does not work as expected with Add-HPOVEnclosure

### ISSUE THREAD

**Issue by arvmig** [HewlettPackard/POSH-HPOneView#29] opened 2015-07-23 21:04 UTC
The following command executed with the -WhatIf parameter.  (POSH-HPOneView v1.20.166.0)

PS> $np4OAs | %{Add-HPOVEnclosure -Monitored -hostname $_."ip address" -username oadmin -password ????? -WhatIf}

Name            : Add
Owner           : administrator
TaskState       : New
PercentComplete : 0
ProgressUpdates : {}
TaskErrors      : {}
Created         : 2015-07-23T19:13:08.470Z
Nodified        : 2015-07-23T19:13:08.470Z
ParentTaskUri   :

Name            : Add
Owner           : administrator
TaskState       : New
PercentComplete : 0
ProgressUpdates : {}
TaskErrors      : {}
Created         : 2015-07-23T19:13:08.670Z
Nodified        : 2015-07-23T19:13:08.670Z
ParentTaskUri   :

**Comment by ChrisLynchHP** [comment] 2015-07-23 21:15
The –WhatIf/-Confirm parameters are to support if an enclosure is currently managed by VCM and if the caller would like to proceed with the Add Enclosure process, which would overwrite the existing VCM configuration.

**Comment by arvmig** [comment] 2015-07-23 22:29
@ChrisLynchHP,
Thanks for the quick response!  I like to use -WhatIf (if available) on cmdlets I'm not familiar with to simulate the outcome.  It would be great if this worked when the "-monitoring" parameter is specified.

**Comment by ChrisLynchHP** [comment] 2015-07-30 18:43
The -WhatIf parameter is not something that is easily implemented.  It is mainly to support CMDLETs that would or could do something destructive.  In the case of Add-HPOVEnclosure, it will be used to prompt the caller/user if they want to add an enclosure with an existing VC Domain without migrating it.  This is by design of the cmdlet.

**Comment by ChrisLynchHP** [comment] 2015-08-02 05:46
I am closing this issue.  If you have further comments or feedback, please reopen it or create a new Issue.

**Closed by ChrisLynchHP** 2015-08-02 05:46 UTC
Labels: Enclosures, question

**Comment by timbing26** [comment] 2015-08-03 01:54
Hi Chris,

This is probably not the right forum. Recently restarted our HP Oneview appliance and it fails to fully start just sits on Starting screen with progress bar about 1/4 way.

Interestingly still getting ilo notifications and can ping appliance.

Any ideas or should I just rebuild or log a call with HP appliance is version 1.20.

Thanks

Tim
