### ISSUE TITLE
Get-HPOVBaseLine Error

### ISSUE THREAD

**Issue by jpaddock1** [HewlettPackard/POSH-HPOneView#356] opened 2018-08-16 11:20 UTC
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
 return from command example

Name        : HP Service Pack for ProLiant
Version     : 2015.10.0
ISOFileName : SPP2015100_2015_0921_6.iso
XMLKeyName  : bp002598
Size        : 5.12GB
Locations   : Internal

### Actual Behavior
```PowerShell
New-Object : Cannot convert argument "6", with value: "5431967744", for "Baseline" to type "System.Int32": "Cannot convert value "5431967744" to type 
"System.Int32". Error: "Value was either too large or too small for an Int32.""
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.410\HPOneView.410.psm1:21046 char:7
+                         New-Object HPOneView.Appliance.Baseline($_baseline.name,
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
 
New-Object : Cannot convert argument "6", with value: "6225240064", for "Baseline" to type "System.Int32": "Cannot convert value "6225240064" to type 
"System.Int32". Error: "Value was either too large or too small for an Int32.""
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.410\HPOneView.410.psm1:21046 char:7
+                         New-Object HPOneView.Appliance.Baseline($_baseline.name,
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
```

### Steps to reproduce

Connect-hpovmgmt (version 4.10)
Get-hpovbaseline

### Version Information

SPP Bundle  Service Pack for ProLiant, 2018.06.0 
(loaded file name into appliance  P09037_001_spp-2018.06.0-SPP2018060.2018_0618.64)

HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  
ApplianceVersion: 4.10.01.348545.00                4.0.1630.2612 

Output from `$PSVersionTable` on your Windows Host:

```PowerShell
Name                           Value                                                                                                                   
----                           -----                                                                                                                   
PSVersion                      4.0                                                                                                                     
WSManStackVersion              3.0                                                                                                                     
SerializationVersion           1.1.0.1                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                         
BuildVersion                   6.3.9600.18773                                                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                                                    
PSRemotingProtocolVersion      2.2             
```

**Comment by ChrisLynchHPE** [comment] 2018-08-16 16:51
Thanks for reporting this.  This is a regression, and the unit tests unfortunately didn't catch.  The baselines we test with are less than 2GB in size.  This will be fixed in the next update.

**Comment by jpaddock1** [comment] 2018-09-12 16:03
[get-hpovbaseline_error.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/2375965/get-hpovbaseline_error.txt)
received the attached error with the latest release

**Comment by ChrisLynchHPE** [comment] 2018-09-13 15:06
Hmm...  I'm struggling trying to figure out what is different with your systems and my dev and test environment as I just cannot reproduce either of these issues.  

How are you installing the library on your systems?

**Comment by jpaddock1** [comment] 2018-09-13 15:30
The original PS modules were scripted install, i have tried removing the modules and manually reinstalling run as Admin. The SPP bundles have also been scripted and manually uploaded

**Comment by ChrisLynchHPE** [comment] 2018-09-13 16:28
Are you using the EXE or getting from the PowerShell Gallery?

**Comment by jpaddock1** [comment] 2018-09-14 07:57
Using the EXE, since the target environment will not have internet access, the ability to bundle and move is required

**Comment by jpaddock1** [comment] 2018-09-14 11:52
Update: using the PS gallery with force option looks to correct the issue in test environment since internet connection available and by downloading nupkg and extracting looks to have worked in the other dev environment but this is not as smooth as process so issue maybe related to EXE install.

**Comment by ChrisLynchHPE** [comment] 2018-09-14 14:19
You can use `Save-Module` to download from the PSGallery, and then move it.  I'll look at the installer, but it should always overwrite destination files, and never look at the file `version`.

So, is the original issue resolved?

**Comment by jpaddock1** [comment] 2018-09-18 08:11
yes, original issue is closed, using the PS gallery resolved the issue. Will review the option of using the save-module for our deployments

**Comment by ChrisLynchHPE** [comment] 2018-09-18 19:57
> using the PS gallery resolved the issue. Will review the option of using the save-module for our deployments

Hmm... Nothing has changed with the installer, so not sure why using it would cause the additional issue you reported.

Closing issue.

**Closed by ChrisLynchHPE** 2018-09-18 19:57 UTC
Labels: 4.10, Firmware, Impact - Medium, Regression
