### ISSUE TITLE
get-hpovalert not accepting pipeline input

### ISSUE THREAD

**Issue by johnreedhpe** [HewlettPackard/POSH-HPOneView#93] opened 2016-04-15 20:24 UTC
I am attempting to use "get-hpovalert" but trying to filter alert by a specific enclosure.

Command:

get-hpovenclosure "ENC03" | get-hpovalert -severity critical

Response is:

You cannot call a method on a null-valued expression.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:46638 char:6

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 

2.0.202
HPE OneView Appliance Version:  

Appliance    Major Minor Software Version X-API Version Model
---------    ----- ----- ---------------- ------------- -----
10.111.13.90 2     00    2.00.02-0219211  200           HP OneView VM - VMware vSphere

Output from `$PSVersionTable` on your Windows Host:

PS H:\> $psversiontable | ft

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.16406
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

**Comment by ChrisLynchHPE** [comment] 2016-04-15 22:51
Thanks.  I have identified the cause of the issue.  A fix will be published shortly to address this.

**Comment by ChrisLynchHPE** [comment] 2016-04-16 03:14
This is fixed in [Release 2.0.340.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.340.0).

**Closed by ChrisLynchHPE** 2016-04-16 03:14 UTC
Labels: Alerting, Bug, Impact - Low
