### ISSUE TITLE
New-HPOVRestore -- Feature request: Accept EULA and set ServiceAccess post-restore

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#147] opened 2016-07-21 14:56 UTC
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
New-HPOVRestore could have the option to accept the EULA and set ServiceAccess?

For me, the New-HPOVRestore throws the buffer error about 70% in, which means I can't set the EULA/SErviceAccess with PowerShell without doing a 10min sleep or something.

-AcceptEULA Yes -ServiceAccess Yes or something?

Excuse me if I'm requesting something strange.

### Actual Behavior
Operator needs to set the EULA and Service Access again in the console post-restore

### Steps to reproduce
New-HPOVRestore
Open appliance console in vSphere or Hyper-V
EULA and Service access need to be accepted/configured

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.530.0
HPE OneView Appliance Version: 2.00.07

**Comment by ChrisLynchHPE** [comment] 2016-07-21 15:32
This is by design. You must accept the EULA, update the Admin password and complete First Time Setup with the `Set-HPOVApplianceNetwork` Cmdlet. What we can look at is validate EULA has ben accepted, and throw an error if it has not.

**Comment by ChrisLynchHPE** [comment] 2016-07-21 15:34
I should have stated you must accept the EULA, set administrator password and appliance network before you attempt a restore.

**Comment by erikgraa** [comment] 2016-07-21 15:36
True, but the EULA/ServiceAccess must be set again after a restore.

**Comment by ChrisLynchHPE** [comment] 2016-07-21 15:37
That is behavior I am not familiar with. I will have look into that further

**Comment by erikgraa** [comment] 2016-07-21 15:39
After the restore the EULA screen will show on the appliance console. You agree. Then the ServiceAccess screen. Press OK after disabling/enabling.

**Comment by erikgraa** [comment] 2016-07-21 18:52
You can still log on to the webui without fault, and it didn't seem like any features weren't activated, so it might just be a bug that EULA+serviceacesst reappears post-restore.

**Comment by ChrisLynchHPE** [comment] 2016-07-21 19:39
We can't seem to replicate this issue. Can you be very detailed in the steps you took to create and then restore he backup? What exactly happens when you execute New-HPOVRestore? Are there any exceptions? If so, we need them in their full content (e.g. $Error | format-list *).

**Comment by erikgraa** [comment] 2016-07-21 19:57
I'll have it for you tomorrow :)

**Comment by erikgraa** [comment] 2016-07-27 15:44
Okay, so what happens is this:

1) Get-HPOVBackup to a -Location
2) New-HPOVRestore -Filename XX.bkp -Confirm:$False -ErrorAction Stop

The progress bar stops at around 70% and I get the "An operation on a socket could not be performed because the system lacked sufficient buffer space or a queue was full <IP>:443.

If I go to the WebUI, the restore keeps progressing whereupon the EULA/ServiceAccess screens appear (similar to a clean install).

From the WebUI you can login without problem. Every configuration item seems restored.

On the restore I just did I got away without the EULA/Serviceaccess screen, but it happens sometimes. Maybe it has to do with when the "buffer space" error occurs -- if it happens before everything is uploaded, then maybe the EULA acceptance isn't transferred.

Looks to be an environmental issue and not to do with OneView though, so I think this issue can be closed.

**Comment by ChrisLynchHPE** [comment] 2016-07-27 16:34
Please know that when you script the EULA and Support Access configuration on an appliance, those screens are not cleared on the appliance console (when you connect to the virtual 'KVM' console of the VM).  Right around 70% the appliance performs a restart of the internal services, as that is were the restore process has completed the restore of the database from the backup file.

I'm going to close this, unless I can reproduce this issue in other testing environments.

**Closed by ChrisLynchHPE** 2016-07-27 16:34 UTC

**Comment by erikgraa** [comment] 2016-07-27 16:39
Ah, that makes a lot of sense.

Any tips on how I can avoid the error output? Pipe to Out-Null?

**Comment by ChrisLynchHPE** [comment] 2016-07-27 16:45
No, because as we have discussed, the "socket" error is environmental.  I have found no supporting documentation that the "socket" error is related to the use of `System.Network.HttpWebRequest` that we use.
