### ISSUE TITLE
New-HPOVServerProfile behavior change

### ISSUE THREAD

**Issue by daveolker** [HewlettPackard/POSH-HPOneView#324] opened 2018-03-03 03:06 UTC
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
The following code successfully creates a Server Profile using the 3.10 library:
```POwerShell
$SY480Gen9SHT   = Get-HPOVServerHardwareTypes -name "SY 480 Gen9 1" -ErrorAction Stop
$Template       = Get-HPOVServerProfileTemplate -Name "HPE Synergy 480 Gen9 RHEL with Local Storage Template" -ErrorAction Stop
$DeploymentPlan = Get-HPOVOSDeploymentPlan -Name "Basic Deployment Plan" -ErrorAction Stop
$Server         = Get-HPOVServer -ServerHardwareType $SY480Gen9SHT -NoProfile -ErrorAction Stop | Select-Object -First 1 
    
$params = @{
    AssignmentType        = "Bay";
    Description           = "HPE Synergy 480 Gen9 Server";
    Name                  = "SP - SY480-RHEL-Local-Storage";
    OSDeploymentPlan      = $DeploymentPlan;
    Server                = $Server;
    ServerProfileTemplate = $Template
}

New-HPOVServerProfile @params | Wait-HPOVTaskComplete
```
### Actual Behavior
Using the 4.00 library it returns the following:

```PowerShell
New-HPOVServerProfile : Enclosure parameter is missing.  Please provide an Enclosure using the -enclosure Parameter and try again.
At C:\Users\daveo\Documents\GitHub\Populate-HPE-Synergy\Populate_HPE_Synergy.ps1:369 char:5
+     New-HPOVServerProfile @params | Wait-HPOVTaskComplete
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Enclosure:String) [New-HPOVServerProfile], ServerProfileResourceException
    + FullyQualifiedErrorId : InvalidEnclosureObject,New-HPOVServerProfile
```

### Steps to reproduce
See above.

In looking at the help page, it does indicate that Enclosure is a required parameter when using the "bay" AssignmentType, but the 3.10 help page contains the same warning but the library processes the request without issue and creates the server profile. 

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`):
15.113.228.220                      LibraryVersion Path                                                    
--------------                      -------------- ----                                                    
ApplianceVersion: 4.00.07.330056.00 4.0.1612.2800  C:\Program Files\WindowsPowerShell\Modules\HPOneView.400

Output from `$PSVersionTable` on your Windows Host:
```PowerShell
Name                           Value                                                                                                          
----                           -----                                                                                                          
PSVersion                      5.1.16299.248                                                                                                  
PSEdition                      Desktop                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                        
BuildVersion                   10.0.16299.248                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                
WSManStackVersion              3.0                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                            
SerializationVersion           1.1.0.1                               
```

**Comment by ChrisLynchHPE** [comment] 2018-03-03 03:23
Your original script is wrong. You do not pass in the SHT when you also provide a Server Profile Template. Remove it and your script will execute correctly.

**Comment by daveolker** [comment] 2018-03-03 03:33
I changed the code to remove the SHT and get the same results:

    $Template       = Get-HPOVServerProfileTemplate -Name "HPE Synergy 480 Gen9 RHEL with Local Storage Template" -ErrorAction Stop
    $DeploymentPlan = Get-HPOVOSDeploymentPlan -Name "Basic Deployment Plan" -ErrorAction Stop
    $Server         = Get-HPOVServer -ServerHardwareType $SY480Gen9SHT -NoProfile -ErrorAction Stop | Select-Object -First 1 
    
    $params = @{
        AssignmentType        = "Bay";
        Description           = "HPE Synergy 480 Gen9 Server";
        Name                  = "SP - SY480-RHEL-Local-Storage";
        OSDeploymentPlan      = $DeploymentPlan;
        Server                = $Server;
        ServerProfileTemplate = $Template
    }

    New-HPOVServerProfile @params | Wait-HPOVTaskComplete


New-HPOVServerProfile : Enclosure parameter is missing.  Please provide an Enclosure using the -enclosure Parameter and try again.
At C:\Users\daveo\Documents\GitHub\Populate-HPE-Synergy\Populate_HPE_Synergy.ps1:369 char:5
+     New-HPOVServerProfile @params | Wait-HPOVTaskComplete
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Enclosure:String) [New-HPOVServerProfile], ServerProfileResourceException
    + FullyQualifiedErrorId : InvalidEnclosureObject,New-HPOVServerProfile



Same code run using the 3.10 library succeeds:

ConnectionID Name           UserName      AuthLoginDomain Default
------------ ----           --------      --------------- -------
1            15.113.228.220 Administrator LOCAL           True   
3/2/2018 7:32:32 PM: Configuring HPE Synergy Appliance
3/2/2018 7:32:32 PM: Creating Local Storage Server Profile

type                    : TaskResourceV2
associatedResource      : @{resourceUri=/rest/server-profiles/2b468c02-0d3e-409e-ade5-26787c374e3e; associationType=MANAGED_BY; 
                          resourceCategory=server-profiles; resourceName=SP - SY480-RHEL-Local-Storage}
taskType                : User
stateReason             : Completed
hidden                  : False
category                : tasks
data                    : 
percentComplete         : 100
taskState               : Completed
taskErrors              : {}
parentTaskUri           : 
associatedTaskUri       : 
completedSteps          : 0
computedPercentComplete : 100
expectedDuration        : 0
progressUpdates         : {@{statusUpdate=Validate configuration.; timestamp=2018-03-03T03:32:39.868Z; id=3269}, @{statusUpdate=Save server 
                          profile definition.; timestamp=2018-03-03T03:32:41.547Z; id=3270}, @{statusUpdate=Reserve connections.; 
                          timestamp=2018-03-03T03:32:42.851Z; id=3271}}
taskOutput              : {}
taskStatus              : Created server profile: SP - SY480-RHEL-Local-Storage.
totalSteps              : 0
userInitiated           : False
name                    : Create
owner                   : Administrator
eTag                    : 8
created                 : 2018-03-03T03:32:39.456Z
modified                : 2018-03-03T03:32:43.806Z
uri                     : /rest/tasks/0052D512-CE6C-4B1C-9987-178578147DDB
ApplianceConnection     : 15.113.228.220

**Comment by ChrisLynchHPE** [comment] 2018-03-03 03:46
The `-ServerHardwareType` and `-AssignmentType Bay` are only for when you do not specify the `-Server` parameter.  Your script should be:

```PowerShell
$Template       = Get-HPOVServerProfileTemplate -Name "HPE Synergy 480 Gen9 RHEL with Local Storage Template" -ErrorAction Stop
$DeploymentPlan = Get-HPOVOSDeploymentPlan -Name "Basic Deployment Plan" -ErrorAction Stop
$Server         = Get-HPOVServer -ServerHardwareType $SY480Gen9SHT -NoProfile -ErrorAction Stop | Select-Object -First 1 

$params = @{
    AssignmentType        = "Server";
    Description           = "HPE Synergy 480 Gen9 Server";
    Name                  = "SP - SY480-RHEL-Local-Storage";
    # OSDeploymentPlan should not be needed as you would have specified this in your SPT.
    # OSDeploymentPlan      = $DeploymentPlan;
    Server                = $Server;
    ServerProfileTemplate = $Template
}

New-HPOVServerProfile @params | Wait-HPOVTaskComplete
```

**Comment by ChrisLynchHPE** [comment] 2018-03-03 03:52
And looking at the Cmdlet code, it is absolutely caused by you passing in the `-AssignmentType Bay` parameter and value.  Change it to `Server` and your script will pass.

**Comment by daveolker** [comment] 2018-03-03 04:26
Thanks Chris.  

I removed all the deployment plan stuff, since as you pointed out that should be in the template.  I put back the SHT because the Get-HPOVServer was referencing that variable, and when it was not defined Get-HPOVServer selected a server of the wrong hardware type and it didn't match the hardware type of the template (it picked a Gen10 blade to apply a Gen9 SPT) and the profile creation failed.

Here's what I have now and it is working as expected:

    $SY480Gen9SHT   = Get-HPOVServerHardwareTypes -name "SY 480 Gen9 1" -ErrorAction Stop
    $Template       = Get-HPOVServerProfileTemplate -Name "HPE Synergy 480 Gen9 RHEL with Local Storage Template" -ErrorAction Stop
    $Server         = Get-HPOVServer -ServerHardwareType $SY480Gen9SHT -NoProfile -ErrorAction Stop | Select-Object -First 1 
    
    $params = @{
        AssignmentType        = "Server";
        Description           = "HPE Synergy 480 Gen9 Server";
        Name                  = "SP - SY480-RHEL-Local-Storage";
        Server                = $Server;
        ServerProfileTemplate = $Template
    }

    New-HPOVServerProfile @params | Wait-HPOVTaskComplete

**Comment by ChrisLynchHPE** [comment] 2018-03-03 05:04
Glad to hear. Closing issue.

**Closed** 2018-03-03 05:05 UTC
Labels: 4.00, Question
