### ISSUE TITLE
Connect-HPOVMgmt - Send-HPOVRequest : The Property 'SslChecked' cannot be found on this object. verify that the property exists and can be set

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#167] opened 2016-08-23 13:05 UTC
Expected Behavior

Connect-HPOVmgmt -hostname <freshly-deployed-appliance-ip/hostname> -username administrator -password admin

Actual Behavior

Send-HPOVRequest : The Property 'SslChecked' cannot be found on this object. verify that the property exists and can be set.
HPOneView.200.psm1:6979 char:34

Seems to encompass several cmdlets.

Steps to reproduce

Connect-HPOVmgmt -hostname <freshly-deployed-appliance-ip/hostname> -username administrator -password admin

Version Information

HPE OneView PowerShell Library Version (Get-HPOVVersion): 2.0.610.0
HPE OneView Appliance Version: 2.00.07

**Comment by ChrisLynchHPE** [comment] 2016-08-23 16:27
You have an unfinished Connection object within the `$ConnectedSessions` global variable.  Did you get an exception within your PowerShell console when trying to connect?

**Comment by ChrisLynchHPE** [comment] 2016-08-23 16:32
And it would be helpful if you could provide a verbose output from the call.  Use the `Start-HPOVLibraryTrace` then `Stop-HPOVLibraryTrace` Cmdlets to capture and generate the verbose output.  Please keep in mind that you cannot use these Cmdlets with the PowerShell ISE at this time (unless you are running PowerShell 5 or 5.1).

**Comment by erikgraa** [comment] 2016-08-23 17:09
$ConnectedSessions is empty, the management client has been booted after installing 2.0.610.3 (what it says in appwiz). The appliance is freshly deployed.

I sent you traces per email.

**Comment by ChrisLynchHPE** [comment] 2016-08-23 17:42
I found the cause of the issue.  It was due to the recent addition of supporting full IPv6 Address support to the Library.  If you use an IP Address, which you are doing, I'm not fully testing if it is an IPv4 versus an IPv6 address.  IPv6 Addresses have to be handled differently than IPv4.  I'll get a fix delivered soon.  In the meantime, the workaround is to add either a DNS A Record or an entry to your systems `$env:Windir\System32\drivers\etc\hosts` file to add a hostname to the IP Address it currently has.  I know it's not ideal for DHCP addresses, but it's the workaround you can use until a fix has been tested and released.

**Comment by ChrisLynchHPE** [comment] 2016-08-23 17:45
I have tested the fix and it works.  I will generate a new installer and post it later today.

**Comment by erikgraa** [comment] 2016-08-23 17:46
Great. I tested with IP because my deploy script uses the IP assigned by DHCP. You are right, everything is alright when using FQDN/hostname.

**Comment by ChrisLynchHPE** [comment] 2016-08-23 17:50
Yeah, it was my mistake.  I forgot to check for the address type, which can be identified.

**Comment by erikgraa** [comment] 2016-08-23 17:51
Using FQDN for the initial config of an appliance doesn't seem to work though, something about the certificate being invalid. I guess because you're connecting with one hostname, and the hostname is something random on first boot (e.g. ci-005056011771)?

**Comment by ChrisLynchHPE** [comment] 2016-08-23 20:15
This is fixed in [Release 2.0.620.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.620.0).

**Comment by erikgraa** [comment] 2016-08-24 19:01
Confirmed to work in 2.0.620.0

**Comment by ChrisLynchHPE** [comment] 2016-08-24 19:12
Excellent.  Closing.

**Closed by ChrisLynchHPE** 2016-08-24 19:12 UTC
Labels: Bug, Core CMDLETs, Impact - Low
