### ISSUE TITLE
OneView 5.4 New-OVUplinkSet  fails with connectionmode cannot be set for this object

### ISSUE THREAD

**Issue by hbxx** [HewlettPackard/POSH-HPOneView#504] opened 2020-09-12 23:01 UTC
Oneview version HPEOneView.540 5.40.2534.2926
command used: 
Get-OVLogicalInterConnectGroup | New-OVUplinkSet -Name 'mgmt' -Type 'ethernet' -Networkset $uplset -UplinkPorts $UpLinkSetPorts -EthMode "Auto"

the issue appears to be:
$_UplinkSetObject does not have connectionmode property. It does have Mode Property

Error thrown:
BuildUplinkSet : Exception setting "connectionMode": "The property 'connectionMode' cannot be found on this object. Verify that the property exists 
and can be set."
At C:\Program Files\WindowsPowerShell\Modules\HPEOneView.540\5.40.2534.2926\HPEOneView.540.psm1:93811 char:46
+ ... UplinkSet = BuildUplinkSet -InputObject $InputObject -Params $UplinkS ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [BuildUplinkSet], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting,BuildUplinkSet

**Comment by ChrisLynchHPE** [comment] 2020-09-14 19:15
Sorry for the issue here.  This was caused by another merge conflict issue that went undetected.  I'm working on publishing an update for this shortly, after unit tests conclude.

This is also found in the 5.00 update I published the other day.

**Comment by ChrisLynchHPE** [comment] 2021-02-09 23:01
This is now addressed in the following releases:

* [5.50.2680.1687](https://www.powershellgallery.com/packages/HPEOneView.550/5.50.2680.1687) 
* [5.40.2681.1725](https://www.powershellgallery.com/packages/HPEOneView.540/5.40.2681.1725)
* [5.30.2682.3811](https://www.powershellgallery.com/packages/HPEOneView.530/5.30.2682.3811)
* [5.20.2684.2161](https://www.powershellgallery.com/packages/HPOneView.520/5.20.2684.2161)
* [5.00.2685.1865](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2685.1865)

Please verify prior to closing this issue.

**Comment by ChristianCarGit** [comment] 2021-03-03 19:07
Working in 5.40.2681.1725. But it is back in the next and newest version 5.40.2689.2416. 

Command used in 5.40.2689.2416: 

# -------------- Attributes for Logical Interconnect Group "test"
$name                               = "test"
$frameCount                         = 1
$bayConfig                          = @{
                Frame1 = @{
                                Bay3 = 'SEVC100f32';
                                Bay6 = 'SEVC100f32'
                }
}
$redundancyType                     = "Redundant"
$fabricModuleType                   = "SEVC100f32"
$InterconnectBaySet                 = 3
$networkLoopProtection              = $True
$InterconnectConsistency            = "Exact"
$lig = New-OVLogicalInterconnectGroup -Name $name -Bays $bayConfig -FabricModuleType $fabricModuleType -fabricredundancy $redundancyType -FrameCount $frameCount -InterConnectBaySet $InterconnectBaySet -enablenetworkLoopProtection:$networkLoopProtection -InterconnectConsistencyChecking $InterconnectConsistency

# -------------- Attributes for Uplink Set "wqec" associated to LogicalInterconnectGroup "test"
$name                               = "wqec"
$uplinkType                         = "Ethernet"
$parentName                         = "test"
$parent                             = Get-OVLogicalInterconnectGroup -Name $parentName
$uplinkPorts                        = "Enclosure1:Bay3:Q1", "Enclosure1:Bay3:Q2", "Enclosure1:Bay3:Q3"
$networks                           = "ESX Mgmt" | Get-OVNetwork
$uplConsistency                     = "Exact"
$ethMode                            = "Auto"
$lacpTimer                          = "Short"
New-OVUplinkSet -InputObject $parent -Name $name -Type $uplinkType -Networks $networks -ConsistencyChecking $uplConsistency -EthMode $ethMode -lacptimer $lacpTimer -UplinkPorts $uplinkPorts

working fine in 5.40.2681.1725.


Getting same error message as above in 5.40.2689.2416.

**Comment by ChrisLynchHPE** [comment] 2022-07-19 18:57
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.

**Closed as completed by ChrisLynchHPE** 2022-07-19 18:57 UTC
Labels: Bug, Impact - High, Uplink Sets, PendingVerification, 5.00, 5.40
