### ISSUE TITLE
New-HPOVServerProfileTemplate specified StorageTargets in New-HPOVServerProfileAttachVolume are not created

### ISSUE THREAD

**Issue by MoritzMuellerHPE** [HewlettPackard/POSH-HPOneView#509] opened 2020-10-19 14:16 UTC
###  Expected Behavior
New-HPOVServerProfileTemplate creates StorageTargets which are specified in New-HPOVServerProfileAttachVolume.

### Actual Behavior
```
HPOneView.520\New-HPOVServerProfileTemplate : Cannot validate argument on parameter 'Hostname'. The argument is null or empty. Provide an argument that is not null or empty, and then try 
the command again.
At C:\Users\muellerm\Desktop\PowerShell_Skripts\Template Hardcoded.ps1:38 char:1
+ HPOneView.520\New-HPOVServerProfileTemplate @params -ApplianceConnect ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-HPOVServerProfileTemplate], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,New-HPOVServerProfileTemplate
```

### Code
```
Connect-HPOVMgmt -Hostname -UserName -AuthLoginDomain -Password 


$Name = "Test2"
$con1 = HPOneView.520\Get-HPOVNetwork -Name "T-Systems POC A"  | HPOneView.520\New-HPOVServerProfileConnection -connectionId 1 -Name net-1 -bootable -priority Primary -ConnectionType Ethernet -PortId "Flb 1:1-a"
$con2 = HPOneView.520\Get-HPOVNetwork -Name "T-Systems POC B"  | HPOneView.520\New-HPOVServerProfileConnection -connectionId 2 -Name net-2 -bootable -priority Secondary -ConnectionType Ethernet -PortId "Flb 1:2-a"
$con3 = HPOneView.520\Get-HPOVNetwork -Name "San-1"  | HPOneView.520\New-HPOVServerProfileConnection -connectionId 3 -Name san1  -ConnectionType FibreChannel -PortId "Flb 1:1-b" -bootable -priority Primary -BootVolumeSource ManagedVolume
$con4 = HPOneView.520\Get-HPOVNetwork -Name "San-2"  | HPOneView.520\New-HPOVServerProfileConnection -connectionId 4 -Name san2  -ConnectionType FibreChannel -PortId "Flb 1:2-b" -bootable -priority Secondary -BootVolumeSource ManagedVolume 
$bl460cG101 = HPOneView.520\Get-HPOVServerHardwareTypes -name "BL460c Gen10 1"
$eg = HPOneView.520\Get-HPOVEnclosureGroup "MCTS Enclosure Group"

$biosSettingss = @(@{id="WorkloadProfile";value="Virtualization-MaxPerformance"},@{id="MinProcIdlePower";value="NoCStates"},@{id="IntelUpiPowerManagement";value="Disabled"},@{id="AdvancedMemProtection";value="FastFaultTolerantADDDC"},@{id="MinProcIdlePkgState";value="NoState"},@{id="EnergyPerfBias";value="MaxPerf"},@{id="UncoreFreqScaling";value="Maximum"},@{id="PowerRegulator";value="StaticHighPerf"},@{id="SubNumaClustering";value="Enabled"},@{id="CollabPowerControl";value="Disabled"},@{id="EnergyEfficientTurbo";value="Disabled"},@{id="NumaGroupSizeOpt";value="Clustered"})

$pool = HPOneView.520\Get-HPOVStoragePool -Name FC_r5 -StorageSystem MCTS-3PAR

$volume1 = HPOneView.520\New-HPOVServerProfileAttachVolume -Name Test -volumeid 1 -ApplianceConnection -Permanent -lunidtype Manual -lunid 0 -ProvisioningType Thin -StoragePool $pool -Capacity 15 -bootable -TargetPortAssignment TargetPorts -TargetAddresses @("0:0:1", "1:0:1", "0:0:2", "1:0:2") 

                                  
$params = @{
    name                = $Name;
    serverHardwareType  = $bl460cG101;
    enclosureGroup      = $eg;
    connections         = $con1, $con2, $con3, $con4;
    ManageBoot          = $True;
    BootMode            = "UEFI";
    pxeBootPolicy       = "IPv4";
    bootOrder           = "PXE";
    SANStorage          = $True;
    HostOStype          = "VMware";
    SANStorageConsistencyChecking = "Minimum";
    StorageVolume       = $volume1;
    Bios                = $True;
    BiosSettings        = $biosSettingss;
}

HPOneView.520\New-HPOVServerProfileTemplate @params -ApplianceConnection -Verbose

Disconnect-HPOVMgmt 
```

### Version Information
```
# Output from $PSVersionTable
Name                           Value                                                                                                                                                        
----                           -----                                                                                                                                                        
PSVersion                      5.1.17763.1007                                                                                                                                               
PSEdition                      Desktop                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                      
BuildVersion                   10.0.17763.1007                                                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                                                              
WSManStackVersion              3.0                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                          
SerializationVersion           1.1.0.1 

# CMDlet Version
HPOneView.520
5.20.2561.3357
```

### Fix
I also tried to fix this issue for me, so I could test the Script. 

```
if ($_Volume.TargetPortAssignmentType)
                                    {

                                        "[{0}] Getting FC network to get associated SAN." -f $MyInvocation.InvocationName.ToString().ToUpper() | Write-Verbose

                                        $_StoragePath.targetSelector = 'TargetPorts'

                                        Try
                                        {

                                            $_ServerProfileConnectionNetwork = Send-HPOVRequest -Uri $_ProfileConnection.networkUri -Hostname $ApplianceConnection

                                        }

                                        Catch
                                        {

                                            $PSCmdlet.ThrowTerminatingError($_)

                                        }

                                        # // TODO: Need to get storage system ports to finalize initiator to target port mapping
                                        #$_StorageSystemExpectedMappedPorts = $_AvailStorageSystems.ports | Where-Object expectedSanUri -eq $_ServerProfileConnectionNetwork.managedSanUri					
			
					$storageSystems = Send-HPOVRequest -uri "/rest/storage-systems" -appliance $ApplianceConnection

                                        ForEach ($_PortID in $_Volume.TargetAddresses)
                                        {
                                            "[{0}] Looking for {1} host port from available storage system." -f $MyInvocation.InvocationName.ToString().ToUpper(), $_PortID | Write-Verbose

                                            if ($StoreServeTargetPortIDPattern.Match($_PortID).Success)
                                            {
                                                $_PortType = 'name'

                                            }

                                            elseif ($WwnAddressPattern.Match($_PortID).Success)
                                            {

                                                $_PortType = 'address'

                                            }

					    $_connectionPortsMapping =  $storageSystems.members.ports | Where-Object "expectedNetworkUri" -eq $_ProfileConnection.networkUri

                                            ForEach ($_HostPort in ($_connectionPortsMapping | Where-Object $_PortType -eq $_PortID))
                                            {
                                                "[{0}] Adding {1} ({2}) host port to targets." -f $MyInvocation.InvocationName.ToString().ToUpper(), $_HostPort.address, $_HostPort.name | Write-Verbose
                                                [void]$_StoragePath.targets.Add($_HostPort.address)
                                            }
						 
                                        }

                                    }
```
This is the code between line 104882-104935 which i changed. And in line 104992 I added:
```
		foreach($item in $_spt.sanStorage.volumeAttachments){
		    $item.PSObject.Properties.Remove('TargetPortAssignmentType')
		    $item.PSObject.Properties.Remove('TargetAddresses')
		}
```
Now it's working fine for me. I wrote the fix in an older version: 5.20.2470.2147, but the latest version (see version in Version Information) has the same issue.

**Comment by ChrisLynchHPE** [comment] 2020-10-19 18:37
I'm not sure your fix addresses the issue.  The issue is with a call within the Cmdlet to the API and the `-Hostname` parameter to `Send-HPOVRequest` is referencing an invalid variable.  So not sure how removing an object property like you did "fixed" this issue.

**Comment by MoritzMuellerHPE** [comment] 2020-10-20 07:01
You are right it didn't really 'fix' the issue, but was more a wrap around. The variable which is empty $_spt.ApplianceConnection isn't  the only problem with the script. If you fix it,  it will abort where i deleted the two parameters. And when you deleted those it will run without an issue, but it doesn't create the Storage Targets.

**Comment by ChrisLynchHPE** [comment] 2020-10-20 23:39
I think I found the source of the issue.  It is two fold; one being the empty variable for another Cmdlet call, and the other is removing helper properties from the storage volume when attaching to the profile or template.

Also, I see you have a bug in your script.  You are attempting to specify multiple bootable connection types.  That is not supported.  You must either use set PXE or BfS, not both.

**Comment by ChrisLynchHPE** [comment] 2021-02-09 22:57
This is now addressed in the following releases:

* [5.50.2680.1687](https://www.powershellgallery.com/packages/HPEOneView.550/5.50.2680.1687) 
* [5.40.2681.1725](https://www.powershellgallery.com/packages/HPEOneView.540/5.40.2681.1725)
* [5.30.2682.3811](https://www.powershellgallery.com/packages/HPEOneView.530/5.30.2682.3811)
* [5.20.2684.2161](https://www.powershellgallery.com/packages/HPOneView.520/5.20.2684.2161)
* [5.00.2685.1865](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2685.1865)

Please verify this is resolved prior to closing this issue.

**Comment by ChrisLynchHPE** [comment] 2022-07-19 18:57
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.

**Closed as completed by ChrisLynchHPE** 2022-07-19 18:57 UTC
Labels: Bug, Server Profiles, Server Profile Templates, PendingVerification, 5.00, 5.20, 5.30, 5.40
