### ISSUE TITLE
New-HPOVLdapDirectory - Send-HPOVRequest times out

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#163] opened 2016-08-01 17:30 UTC
### Expected Behavior
New-HPOVLdapDirectory without timeouts

### Actual Behavior
New-HPOVLdapDirectory throws several errors despite the command actually completing successfully.

This happens on both $_validateresp and $_resp.
```
Send-HPOVRequest: The operation has timed out
```

Unfortunately this seems to be a terminating error. On reviewing Get-HPOVLdapDirectory later on, the directory has been added.

### Steps to reproduce
It might just be my environment. Sometimes I'm able to do the command successfully with no errors, other times the above happens.

### Comment
Is it possible to make the timeouts non-terminating so the script can go on and poll Get-HPOVLdapDirectory before proceeding?

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.576.0
HPE OneView Appliance Version: 2.00.07

**Comment by ChrisLynchHPE** [comment] 2016-08-01 17:32
No.  There have been reports of timeouts from API calls, but I cannot just arbitrarily not-terminate timeout errors.  And those reports have been specific to the environment, not the Cmdlet.

**Comment by erikgraa** [comment] 2016-08-01 17:34
ErrorAction SilentlyContinue is not heeded by the cmdlet?

**Comment by ChrisLynchHPE** [comment] 2016-08-01 17:50
Not using the method we use to generate errors.  Can you provide more information on the environment?  Is this a Hyper-V environment, where you are hosting the VM, and then running the PowerShell scripts from the same Windows host? Because that is where I see the majority of the timeouts occur, and so far have no other solution to that problem than to recommend you run your scripts elsewhere.

**Comment by erikgraa** [comment] 2016-08-01 20:19
HPOneView.200 is run from a separate computer.

I don't understand what it's timing out on.

Can the wait before a timeout event be increased?

Why would it time out when it /does/ complete the objective of adding a directory?

**Comment by ChrisLynchHPE** [comment] 2016-08-01 20:47
Send-HPOVRequest uses the `System.Network.HttpWebRequest` managed class from the .Net Framework.  The timeout is when the API request is made, but then times out waiting for the API to reply.  Timeout is already increased beyond the 10 second default, to 20 seconds.

> Why would it time out when it /does/ complete the objective of adding a directory?

That is the unknown.  I cannot explain why that happens.  I've looked into it quite indepth, and have not been able to reproduce it on any level of consistency.  It appears to be environment specific, but I don't have the exact data points to back that up, other than this is a severely inconsistent behavior.

**Comment by erikgraa** [comment] 2016-08-01 21:16
I'll do some more experimenting!

**Comment by erikgraa** [comment] 2016-08-23 18:07
Update: Haven't been able to look at this due to other projects, but I'll check when I deploy the next appliance.

**Comment by erikgraa** [comment] 2016-08-24 19:01
Well, after a lot of experimentation, I think we have to assume this is an environmental issue. Sometimes it works, other times it doesn't. Issue can be closed.

**Comment by ChrisLynchHPE** [comment] 2016-08-24 19:03
Closing.

**Closed by ChrisLynchHPE** 2016-08-24 19:03 UTC
