### ISSUE TITLE
Connect-HPOVMgmt (Feature Request) -- Login using Windows Authentication similar to Connect-VIServer in PowerCLI/vSphere

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#127] opened 2016-06-21 17:52 UTC
I want to be able to type Connect-HPOVMgmt -Appliance <hostname> and if no further credentials/parameters (Username, Password) are passed, it would be great if the Cmdlet used the currently logged in user's credentials to log in, assuming AD-integration is set-up and the user is in an associated security group assigned to a role.

### Expected Behavior

Being able to connect with a server account that's performing a scheduled task without passing the password insecurely.

### Actual Behavior

Difficulty setting up scheduled tasks with domain service accounts

### Steps to reproduce

N/A

### Version Information
N/A

**Comment by ChrisLynchHPE** [comment] 2016-06-21 17:55
This is a duplicate of #51.  HPE OneView does not support Kerberos authentication, and Microsoft does not provide a method to obtaining a users password from their Windows session.  Yes, OneView supports Active Directory, but only as a Secure LDAP server.

**Comment by erikgraa** [comment] 2016-06-21 17:57
Didn't see that one.

No chance of Kerberos support?

What are HP's suggestions for running Scheduled Tasks securely, ie. without exposing passwords?

**Comment by ChrisLynchHPE** [comment] 2016-06-21 18:00
Not unless the HPE OneView product itself supports Kerberos authentication.

As for running your scripts, use the `ApplianceBackup_Sample.ps1` as a guide.  There are techniques to store an account password securing on a local system for script execution, which you will have to provide the password at least once.  I us that technique for automating the signing process HPE provides use to digitally sign the components of the library.  If you can't find a good example, I could dig one up for you.

**Comment by erikgraa** [comment] 2016-06-21 18:04
I suppose it is possible to get a SecureString object, store it in a file, read it back when needed and decrypt it.

It is a technique that opens the password up for decryption by anyone who logs on or has access to files on that system though. However, it is better than plaintext.

My problem is that I need to not only do backup using a scheduled task, I need to download the audit log regularly, and the audit log requires Infrastructure administrator to download. Ergo the service account needs the highest level role on the system.

**Comment by ChrisLynchHPE** [comment] 2016-06-21 18:07
The example I would provide uses RSA system encryption, using a randomly generated passkey that the PC has stored in its Secure Store.  So even if someone gained file system access, they couldn't decrypt the file for the password without your PC.  And if they had your PC, well, that's a different issue altogether.

The net of this is that I can't implement Kerberos authentication without OneView supporting it.  What I have provided you is the only method to automate.

**Comment by erikgraa** [comment] 2016-06-21 18:34
Sounds like a good approach! I'll look into it.

**Closed** 2016-06-22 01:08 UTC
