### ISSUE TITLE
Another issue with New-HPOVServerProfileTemplate and -localstorage

### ISSUE THREAD

**Issue by tknightblc** [HewlettPackard/POSH-HPOneView#88] opened 2016-04-08 01:30 UTC
Now have my serverprofile templates working with all params but anything to do with -localstorage - when I invoke -LocalStorage and any options associated to that (with or without -Logicaldisk) I get a New-HPOVServerProfileTemplate : Unrecognized JSON field error. All looks good to me. Any help appreciated.

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> Get-HPOVVersion

PowerShell Library Version : 2.0.296.0
Library Path               : C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $PSVersionTable

Name  : PSVersion
Value : 4.0

Name  : WSManStackVersion
Value : 3.0

Name  : SerializationVersion
Value : 1.1.0.1

Name  : CLRVersion
Value : 4.0.30319.42000

Name  : BuildVersion
Value : 6.3.9600.16406

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0}

Name  : PSRemotingProtocolVersion
Value : 2.2

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $params

Name  : LogicalDisk
Value : @{driveNumber=; driveName=My local disk; bootable=False; raidLevel=RAID1; numPhysicalDrives=2; driveTechnology=SasHdd}

Name  : bootOrder
Value : HardDisk

Name  : bios
Value : True

Name  : enclosureGroup
Value : @{type=EnclosureGroupV200; uri=/rest/enclosure-groups/78dec4f7-c6c2-4def-a612-2c7891ed6a45; category=enclosure-groups; name=ESX-Enclosure; 
        created=2016-03-29T22:40:02.146Z; modified=2016-04-07T22:39:19.084Z; eTag=2016-04-07T22:39:19.084Z; status=OK; state=Normal; 
        enclosureTypeUri=/rest/enclosure-types/c7000; stackingMode=Enclosure; portMappingCount=8; portMappings=System.Object[]; interconnectBayMappingCount=8; 
        interconnectBayMappings=System.Object[]; ipAddressingMode=External; ipRangeUris=System.Object[]; powerMode=; description=; enclosureCount=1; 
        associatedLogicalInterconnectGroups=System.Object[]; ApplianceConnection=}

Name  : LocalStorage
Value : True

Name  : name
Value : Test22

Name  : HideUnusedFlexnics
Value : True

Name  : pxeBootPolicy
Value : IPv4ThenIPv6

Name  : manageboot
Value : True

Name  : bootMode
Value : UEFI

Name  : serverHardwareType
Value : @{type=server-hardware-type-4; category=server-hardware-types; name=BL460c Gen9 1; description=; 
        uri=/rest/server-hardware-types/FB3061E8-5DC3-4C32-9961-8C6EEC56786C; eTag=1459291537489; created=2016-03-29T22:45:29.539Z; modified=2016-03-29T22:45:37.489Z; 
        model=ProLiant BL460c Gen9; formFactor=HalfHeight; storageCapabilities=; biosSettings=System.Object[]; bootModes=System.Object[]; 
        pxeBootPolicies=System.Object[]; adapters=System.Object[]; bootCapabilities=System.Object[]; capabilities=System.Object[]; ApplianceConnection=}

Name  : connections
Value : {@{id=1; functionType=Ethernet; name=; portId=Auto; networkUri=/rest/ethernet-networks/341d18c4-fb07-43ac-a46d-cfd0ff7fe1af; requestedMbps=1000; boot=; 
        macType=Virtual; mac=; wwpnType=Virtual; wwnn=; wwpn=; ApplianceConnection=}, @{id=2; functionType=Ethernet; name=; portId=Auto; 
        networkUri=/rest/ethernet-networks/229adda7-cedc-4c74-ab5d-03152be01a40; requestedMbps=1000; boot=; macType=Virtual; mac=; wwpnType=Virtual; wwnn=; wwpn=; 
        ApplianceConnection=}, @{id=3; functionType=FibreChannel; name=; portId=Auto; networkUri=/rest/fc-networks/12e0d358-e587-4d5a-ab81-da5cec33a950; 
        requestedMbps=4000; boot=; macType=Virtual; mac=; wwpnType=Virtual; wwnn=; wwpn=; ApplianceConnection=}, @{id=4; functionType=FibreChannel; name=; portId=Auto; 
        networkUri=/rest/fc-networks/133e89d2-4a37-4144-b55d-cfa054227c53; requestedMbps=4000; boot=; macType=Virtual; mac=; wwpnType=Virtual; wwnn=; wwpn=; 
        ApplianceConnection=}...}

Name  : Initialize
Value : True

Name  : biossettings
Value : {System.Collections.Hashtable, System.Collections.Hashtable, System.Collections.Hashtable}

Name  : ApplianceConnection
Value : HPOneView.Appliance.Connection

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> New-HPOVServerProfileTemplate @params | Wait-HPOVTaskComplete
New-HPOVServerProfileTemplate : Unrecognized JSON field. The field named importConfiguration near line 1, column 652 is not a valid field in this JSON object.
At line:1 char:1
+ New-HPOVServerProfileTemplate @params | Wait-HPOVTaskComplete
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [New-HPOVServerProfileTemplate], InvalidOperationException
    + FullyQualifiedErrorId : InvalidAuthOperation,New-HPOVServerProfileTemplate
 

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $error | % { Format-List -InputObject $_ * } 

PSMessageDetails      : 
Exception             : System.InvalidOperationException: Unrecognized JSON field. The field named importConfiguration near line 1, column 652 is not a valid field in 
                        this JSON object.
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
TargetObject          : Send-HPOVRequest
CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [Send-HPOVRequest], InvalidOperationException
FullyQualifiedErrorId : InvalidAuthOperation,Send-HPOVRequest
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5469
                        at New-HPOVServerProfileTemplate<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 40242
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PSMessageDetails      : 
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "GetResponse" with "0" argument(s): "The remote server returned an 
                        error: (400) Bad Request." ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
                           at System.Net.HttpWebRequest.GetResponse()
                           at CallSite.Target(Closure , CallSite , HttpWebRequest )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : WebException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5068
                        at New-HPOVServerProfileTemplate<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 40242
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $error | % { $_.ScriptStackTrace } 
at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5469
at New-HPOVServerProfileTemplate<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 40242
at <ScriptBlock>, <No file>: line 1
at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5068
at New-HPOVServerProfileTemplate<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 40242
at <ScriptBlock>, <No file>: line 1

**Comment by ChrisLynchHPE** [comment] 2016-04-08 02:47
This is a known condition, and will be fixed in the next release.

**Comment by ChrisLynchHPE** [comment] 2016-04-08 03:37
Also, this is a duplicate of #81.  Closing. Please reference the original issue.

**Closed by ChrisLynchHPE** 2016-04-08 03:37 UTC
Labels: Bug, Impact - Medium, Server Profiles
