### ISSUE TITLE
Remove-HPOVServerProfileTemplate "name" alias

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#213] opened 2017-01-12 08:23 UTC
Should the "name" alias in Remove-HPOVServerProfileTemplate be removed?

Remove-HPOVServerProfileTemplate uses a server template object and not the name of the template, so having an option/ alias of name is likely to cause errors (as the scripter will supply the name and not the object)

The Help:
    -ServerProfileTemplate <Object>
        Aliases [-spt, -name]
        The server profile tempalte object(s) or name(s) to be removed.

### Version Information
PowerShell Library Version : 3.0.1191.2858
Library Path               : C:\Program Files\WindowsPowerShell\Modules\HPOneView.300

**Comment by ChrisLynchHPE** [comment] 2017-01-12 21:08
Duplicate of #212 Closing.

**Closed by ChrisLynchHPE** 2017-01-12 21:08 UTC
Labels: Bug, Documentation
