### ISSUE TITLE
Add-HPOVBaseline -- fails if you're uploading baselines back to back

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#138] opened 2016-07-13 13:01 UTC
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Firmware being uploaded successfully one after the other.

### Actual Behavior
After the first ISO has been uploaded (Add-HPOVBaseline returns), I get the following error:

Send-HPOVrequest: an operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full on <ApplianceIP>:443

Maybe I need a Wait-HPOVTaskComplete or a sleep or something? Feels like a bad workaround.

### Steps to reproduce
My script is this and C:\Firmware contains two different HP SPP ISOs.

$FirmwarePath = "C:\Firmware"
$Files = $(Get-ChildItem $FirmwarePath).FullName
Foreach($File in $Files) {
  Add-HPOVBaseline -File $File -ApplianceConnection $A
}

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.500.0
HPE OneView Appliance Version: 2.00.07
Output from `$PSVersionTable` on your Windows Host:

**Comment by ChrisLynchHPE** [comment] 2016-07-13 17:27
The process is already an asynchronous task, and the Cmdlet waits for the task to complete anyhow.  From the error message, it looks to be an OS level issue:  http://stackoverflow.com/questions/17167977/httpwebrequest-issue-system-lacked-sufficient-buffer-space-or-because-a-queue-w

**Comment by ChrisLynchHPE** [comment] 2016-07-13 17:30
Also, there are some forums posts you may find that talks about `KeepAlive` being set to `True` (which is part of the thread discussion I linked to above).  We use the `System.Net.HttpWebRequest` class object for HTTP connections.  It defaults to HTTP/1.1, which `KeepAlive` already defaults to `True`.

**Comment by erikgraa** [comment] 2016-07-13 21:02
I see. So the OS has basically run out of memory to do the second upload. My first upload of 6GB goes fine. Hopefully there's another fix other than just increasing memory, I don't see why it shouldn't free up that memory once the upload is completed.

By the way, is the firmware baseline repo supposed to only be 12GB, or does that increase dynamically?

**Comment by ChrisLynchHPE** [comment] 2016-07-13 21:38
The process that handles the file upload only uses a 4MB buffer, and it is reused every time the file is read.  The HTTPS connection is persistent, which means that the session doesn't initiate  new TCP connection just to continue the request (or file upload).  There very well could be a garbage collection issue with the .Net Framework you have installed.  Can you provide more detail about your system?  What Windows version?  What .NetFramework?

The Baseline repository is currently locked to 12GB.  We announced 3.0 back in June at HPE Discover Las Vegas.  That release will allow you to increase the VMDK/VHD from 170GB to 275GB, and will then increase the repository from 12GB to 100GB.  There is no in between.

**Comment by erikgraa** [comment] 2016-07-13 21:42
This was windows server 2012, .net 4.6. I was going to try tomorrow on a w7 client instead, but I don't expect it to act differently. If I don't get it to work I'll just have to restrict to a single upload during install to work around this.

PSVersion 4.0
WSAnStackVersion 3.0
SerializationVersion 1.1.0.1
CLRVersion 4.0.30319.42000
Buildversion 6.3.9600.17400

**Comment by ChrisLynchHPE** [comment] 2016-07-13 21:44
I test with Windows Server 2012 R2 and .Net 4.6 as well.  I'll see if I can reproduce the issue you are experiencing.

**Comment by erikgraa** [comment] 2016-07-14 09:46
Tried on a different server and it worked without fault. Attributable to some OS level issue on one of the Windows servers and can be closed.

**Comment by ChrisLynchHPE** [comment] 2016-07-14 19:09
Closing.

**Closed by ChrisLynchHPE** 2016-07-14 19:09 UTC
