### ISSUE TITLE
Retrieving the Appliance Service Console Access allowment using the Get-OVApplianceServiceConsoleAccess Cmdlet results in error

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#521] opened 2020-11-19 10:10 UTC
### Expected Behavior

Using ```Get-OVApplianceServiceConsoleAccess``` cmdlet should report the correct Appliance Service Console Access allowment setting.

### Actual Behavior

```PowerShell 
Get-OVApplianceServiceConsoleAccess

Get-OVApplianceServiceConsoleAccess : Argument types do not match
```
Output from the Error-variable:

![image](https://user-images.githubusercontent.com/20067955/99652199-d476aa00-2a57-11eb-8a7b-2339d898d21f.png)

### Steps to reproduce

```PowerShell

Connect-OVMgmt [..]

Get-OVApplianceServiceConsoleAccess
```

### Version Information
HPE OneView PowerShell Library Version: ```LibraryVersion: 5.50.2604.1781```

HPE OneView Appliance Version: ```ApplianceVersion: 5.50.00.426657.00```

Output from `$PSVersionTable` on your Windows Host:

```PowerShell
PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by ChrisLynchHPE** [comment] 2020-11-19 17:09
I am not able to reproduce this.  Can you provide the output from:

```powershell
Send-OVRequest -Uri /rest/appliance/settings/serviceaccess
```

It should be a boolean response; either `True` or `False`.

**Comment by erikgraa** [comment] 2020-11-19 17:25
```Send-OVRequest -Uri /rest/appliance/settings/serviceaccess``` returns the prompt with no output, but when I pass the ```-Verbose``` parameter I see there's a "BoolResponse": false" The FinalResponse is false.

![image](https://user-images.githubusercontent.com/20067955/99701266-8207ae80-2a94-11eb-9197-a4884a98e188.png)

![image](https://user-images.githubusercontent.com/20067955/99701293-8d5ada00-2a94-11eb-84da-0025bf00d32e.png)

```Send-OVRequest -Uri /rest/appliance/ssh-access``` returns a SshAccess type PSCustomObject. When passing the ```-Verbose``` parameter I see there's a FinalResponse json output.

![image](https://user-images.githubusercontent.com/20067955/99701246-7caa6400-2a94-11eb-8b5b-6d916c978cf8.png)

**Comment by ChrisLynchHPE** [comment] 2020-11-19 17:49
Thanks.  This is because PowerShell is handling `False` a bit differently than expected.  This will be fixed in the next round of library update planned for after the US holiday break.

**Comment by erikgraa** [comment] 2020-11-24 02:01
I have tested this to great success!

**Comment by ChrisLynchHPE** [comment] 2021-02-09 22:39
This is now addressed in the following releases:

* [5.50.2680.1687](https://www.powershellgallery.com/packages/HPEOneView.550/5.50.2680.1687) 
* [5.40.2681.1725](https://www.powershellgallery.com/packages/HPEOneView.540/5.40.2681.1725)
* [5.30.2682.3811](https://www.powershellgallery.com/packages/HPEOneView.530/5.30.2682.3811)
* [5.20.2684.2161](https://www.powershellgallery.com/packages/HPOneView.520/5.20.2684.2161)
* [5.00.2685.1865](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2685.1865)

Closing.

**Closed as completed by ChrisLynchHPE** 2021-02-09 22:39 UTC
Labels: Bug, NeedMoreInformation, 5.00, 5.20, 5.30, 5.40, 5.50
