### ISSUE TITLE
Write-host is a pain

### ISSUE THREAD

**Issue by zdzichajec** [HewlettPackard/POSH-HPOneView#173] opened 2016-09-28 11:23 UTC
If code is Executed non interactive it fails because of White-host has no host to write to. Due to this we are not able to execute scheduled actions

### Expected Behavior
Wien -noninteractive param is provided , module sound Stilo work

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):
HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:

**Comment by zdzichajec** [comment] 2016-09-28 11:25
*module should still work (damn autocorrect)

**Comment by ChrisLynchHPE** [comment] 2016-09-28 15:59
Use the (`Enable-HPOVMSDSC`)[https://github.com/HewlettPackard/POSH-HPOneView/wiki/Enable-HPOVMSDSC] Cmdlet. It will overload 'Write-Host' with 'Write-Verbose' which will provide what you are looking for. Just know that enabling this will be on a per user basis, as the setting is stored in HKCU. The documentation calls this out so you could pre-create this for other user accounts, like service accounts.

**Comment by zdzichajec** [comment] 2016-09-28 17:48
That's terrible approach ;)
Much easier would be to add a param to module load (like [switch]$Quiet)
In my environment I'm unable to precreate such entry.
Gonna have to prepare modified version of this module.
Cheers

**Comment by ChrisLynchHPE** [comment] 2016-09-28 17:55
I and others disagree that this is a "wrong approach".  PowerShell Modules should not have parameters.  It makes discovery of them extremely difficult.  Sure, there is the `-ArgumentList` parameter for `Import-Module`.  But no easy way for someone to discover parameters for a PSM1, let alone the parameter is only available for Script Modules (PSM1) anyhow.

And why can you not create an HKey_Current_User key?  Any user can modify their own registry hive, and even use `reg.exe -import` to import a registry configuration to HKCU?

**Comment by CermakPOI** [comment] 2016-09-29 08:10
You could add the Quiet Parameter to the Connect-HPOVMgmt, this i needed anyway as the first function.
Anyway instead of overloading the Write-Host (in my opinion a really bad idea) and parametrizing it with a User-registry key, i would have created a new function (Write-HPOVHost,...) which uses a global Variable like -Quiet

**Comment by ChrisLynchHPE** [comment] 2016-09-29 15:50
The use case isn't to overload Write-Host for interactive purposes.  It's to handle the case where there is no `host` to write to, or a user is trying to use say Microsoft System Center Operations Manager which requires no `Write-Host` output.  To control this behavior on a per-user basis, it is controlled by a Registry Key value.  I'm finding it hard to understand why this is "such a bad idea".

**Comment by zdzichajec** [comment] 2016-09-29 17:55
In my project I have no access to production. I have to prepare scheduled tasks executed by service account. You Can't login to host using service account. It's doable to manage this but I have to instruct provisioning team to prepare such thing (and provisioning is not much techy). Later on, any member of operations may want to prepare adhoc sccripts execution that need to be executed non interactively. Now You want me to first instruct these people to add a hack to registry...
Thant's not enterprise ready.
Anyway, I really see no reason to blast series of Write-Hosts at the begining of module loading. Noone reads that ;)

**Comment by ChrisLynchHPE** [comment] 2016-09-29 18:11
> Anyway, I really see no reason to blast series of Write-Hosts at the begining of module loading. Noone reads that ;)

I'm sorry, but that's your opinion.  There are plenty of users that use the library for interactive purposes.

I just tested this, albeit on a Windows 10 system with PowerShell 5.1, and I wasn't able to reproduce your original issue.  I executed the following successfully, which produced the txt file I wanted:

```Cmd
C:\Users\User>powershell -NonInteractive -Command "& {ipmo HPOneView.200; connect-hpovmgmt -hostname appliancename -username administrator -password password; get-hpovnetwork > C:\temp\networks_list.txt}"
```

Here are the contents of the `networks_list.txt` file:
```PowerShell
    Type: Ethernet


Name                    Status Purpose     Type   VlanID Smartlink PrivateNetwork PreferredBandwidth MaxBandwidth
----                    ------ -------     ----   ------ --------- -------------- ------------------ ------------
Heartbeat               OK     Management  Tagged 101    True      False          2500               10000           
Live Migration          OK     VMMigration Tagged 100    True      False          2500               10000       
My Vlan 501             OK     General     Tagged 501    True      False          2500               20000       
New Unassigned Network1 OK     General     Tagged 1001   True      False          2500               20000       
VLAN 10-A               OK     General     Tagged 10     True      False          2500               10000       
VLAN 10-B               OK     General     Tagged 10     True      False          2500               10000       
VLAN 1-A                OK     General     Tagged 1      True      False          2500               10000       
VLAN 1-B                OK     General     Tagged 1      True      False          2500               10000       
VLAN 20-A               OK     General     Tagged 20     True      False          2500               10000       
VLAN 20-B               OK     General     Tagged 20     True      False          2500               10000       
VLAN 30-A               OK     General     Tagged 30     True      False          2500               10000       
VLAN 30-B               OK     General     Tagged 30     True      False          2500               10000       
VLAN 40-A               OK     General     Tagged 40     True      False          2500               10000       
VLAN 40-B               OK     General     Tagged 40     True      False          2500               10000       
VLAN 50-A               OK     General     Tagged 50     True      False          2500               10000       
VLAN 50-B               OK     General     Tagged 50     True      False          2500               10000       
Vlan 60-B               OK     General     Tagged 60     True      False          2500               20000       




    Type: Fibre Channel


Name           Status Type         Typical Bandwidth Max Bandwidth Auto Login Redistribution Link Stability Interval Managed   
                                                                                                                     SAN       
----           ------ ----         ----------------- ------------- ------------------------- ----------------------- ----------
DirectAttach A OK     DirectAttach 2500              10000         False                     0                                 
DirectAttach B OK     DirectAttach 2500              10000         False                     0                                 
Fabric A       OK     FabricAttach 2500              10000         False                     0                       SAN1_0    
Fabric B       OK     FabricAttach 2500              10000         False                     0                       SAN1_1    
```

Can you provide any screenshots or further data points that the module fails to load for you or you get an exception when using the `-NonInteractive` parameter switch for `PowerShell.exe`?

**Comment by ChrisLynchHPE** [comment] 2016-09-29 18:18
And just successfully tested on a Windows Server 2012 R2 system with PowerShell 4.0 using the very same command I used on my Windows 10 system.

**Comment by zdzichajec** [comment] 2016-09-30 07:07
I'm executing command through corporate scheduler
powershell.exe -noninteractive -File c:\path\to\script.ps1
I get error:
The Connect-HPOVMgmt command was found in the module HPOneView.200, but the module could not be loaded.

Executing manually (e.g. from cmd) this line will work for me as well.

**Comment by ChrisLynchHPE** [comment] 2016-09-30 15:49
Are you sure you are executing the 64-bit version of PowerShell.exe?  Are you trying to load the module on a 32-bit OS?  If you are trying to start the 32-bit version of PowerShell, we don't support it as the module has a number of 64-bit Integers that are required.  As I showed above, I am unable to reproduce your issue.

**Comment by ChrisLynchHPE** [comment] 2016-10-27 05:31
I'm closing this issue due to no further activity.  We can re-open this if you are still experiencing an issue.

**Closed by ChrisLynchHPE** 2016-10-27 05:31 UTC
