### ISSUE TITLE
Get-HPOVServer returns only 10 of 12 servers in a Scope when using -Name "*" and -Scope.

### ISSUE THREAD

**Issue by ronanmcallister** [HewlettPackard/POSH-HPOneView#271] opened 2017-05-10 23:35 UTC
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior

OneView 3.00 POSH Get-HPOVServer cmdlet should return all servers contained within a Scope, when the cmdlet's "-Name" parameter contains the wildcard "*", and the -Scope parameter contains a number of servers above 10.   A simple example:

$scope = Get-HPOVScope -Name "12 Servers" #OneView Scope Name Anonymized
Get-HPOVServer -Name "*" -Scope $scope

The entire 12 servers are expected as output.

### Actual Behavior

Only 10 of the 12 servers are output from the above in my case.   I have confirmed all 12 servers are in the Scope.

Note: As the above only returns 10 of 12, I must thereafter execute Get-HPOVServer -Name twice to get the additional two (missing) Server Hardware:

Get-HPOVServer -Name "ILOUSE11111AB" #Server HW Name is Anonymized
Get-HPOVServer -Name "ILOUSE11111AD" #Server HW Name is Anonymized

### Steps to reproduce

Create a Scope containing over 10 DL380p Gen8 Rack servers -- i.e. 12 or more.
Run the above or similar script.

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):

PowerShellLibraryVersion : 3.0.1293.3770
LibraryPath              : C:\Program Files\WindowsPowerShell\Modules\HPOneView.300

HPE OneView Appliance Version:  

Output from `$PSVersionTable` on your Windows Host:
PowerShellLibraryVersion : 3.0.1293.3770
LibraryPath              : C:\Program Files\WindowsPowerShell\Modules\HPOneView.300

**Comment by ChrisLynchHPE** [comment] 2017-06-10 21:54
I cannot seem to reproduce this.  I just added 14 server resources to a new scope:

`New-HPOVScope -Name Servers'

I then added all 14 of my servers to the new scope:

`Get-HPOVScope -Name Servers | Add-HPOVResourceToScope -Resource (Get-HPOVServer)`

I then used the new scope to get my servers:

```PowerShell
[PS] C:\> $Scope = Get-HPOVScope -Name Servers
[PS] C:\> Get-HPOVServer -Scope $Scope

Name          Status  Power Serial Number Model       ROM                  iLO       Server Profile License
----          ------  ----- ------------- -----       ---                  ---       -------------- -------
Encl1, bay 1  Warning Off   SGH100X7RN    BL660c Gen9 I38 v1.30 08/03/2014 iLO4 2.20 No Profile     OneViewNoiLO
Encl1, bay 11 Warning On    SGH100X5RN    BL460c Gen9 I36 v1.30 08/26/2014 iLO4 2.50 Hyp-Clus-01    OneViewNoiLO
Encl1, bay 12 Warning Off   SGH101X5RN    BL460c Gen9 I36 v1.30 08/26/2014 iLO4 2.50 No Profile     OneViewNoiLO
Encl1, bay 13 Warning Off   SGH102X5RN    BL460c Gen9 I36 v1.30 08/26/2014 iLO4 2.20 No Profile     OneViewNoiLO
Encl1, bay 14 Warning Off   SGH103X5RN    BL460c Gen9 I36 v1.30 08/26/2014 iLO4 2.20 No Profile     OneViewNoiLO
Encl1, bay 15 Warning Off   SGH104X5RN    BL460c Gen9 I36 v1.30 08/26/2014 iLO4 2.20 No Profile     OneViewNoiLO
Encl1, bay 16 Warning Off   SGH105X5RN    BL460c Gen9 I36 v1.30 08/26/2014 iLO4 2.20 No Profile     OneViewNoiLO
Encl1, bay 2  Warning Off   SGH101X7RN    BL660c Gen9 I38 v1.30 08/03/2014 iLO4 2.20 No Profile     OneViewNoiLO
Encl1, bay 3  Warning Off   SGH100X8RN    BL460c Gen8 I31 09/30/2011       iLO4 2.20 No Profile     OneView
Encl1, bay 4  Warning Off   SGH101X8RN    BL460c Gen8 I31 09/30/2011       iLO4 2.20 No Profile     OneView
Encl1, bay 5  Warning Off   SGH102X8RN    BL460c Gen8 I31 09/30/2011       iLO4 2.20 No Profile     OneView
Encl1, bay 6  Warning Off   SGH103X8RN    BL460c Gen8 I31 09/30/2011       iLO4 2.20 No Profile     OneView
Encl1, bay 7  Warning Off   SGH104X8RN    BL460c Gen8 I31 09/30/2011       iLO4 2.20 No Profile     OneView
Encl1, bay 8  Warning Off   SGH105X8RN    BL460c Gen8 I31 09/30/2011       iLO4 2.20 No Profile     OneView
```

**Comment by ChrisLynchHPE** [comment] 2018-09-28 04:10
Closing due to no further activity.

**Closed by ChrisLynchHPE** 2018-09-28 04:10 UTC
