### ISSUE TITLE
Issue with New-HPOVServerProfileTemplate - does not let you create unmanaged boot mode with newest 3.10 library

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#352] opened 2018-07-31 15:21 UTC
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior

New-HPOVServerProfileTemplate [..Name,Description,Firmware..] -ManageBoot:$False -BootMode Unmanaged

Should create a template wherein no boot settings are configured

### Actual Behavior

New-HPOVServerProfileTemplate: The specification of boot mode and boot order settings are not allowed i the manage boot mode feature is disabled.

Works fine with version 3.0.1264.2772, not with 3.10.1731.3550.

### Steps to reproduce

New-HPOVServerProfileTemplate [..Name,Description,Firmware..] -ManageBoot:$False -BootMode Unmanaged

using version 3.10.1731.3550 (HPOneView.310)

```PowerShell
taskoutput: $null
taskstatus:Unable to create server profile template
message: The specification of boot mode and boot order settings are not allowed i the manage boot mode feature is disabled.
```

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`): 3.10.1731.3550
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  3.10.10
Output from `$PSVersionTable` on your Windows Host:

```PowerShell
# Output from $PSVersionTable
```
PSVersion: 4.0
CLRVersion: 4.0.30319.34014

**Comment by ChrisLynchHPE** [comment] 2018-08-03 20:44
Omit `-BootMode` parameter in your script call.  You shouldn't have been specifying that anyhow.

**Comment by erikgraa** [comment] 2018-08-06 15:25
I want the boot settings unset/unmanaged, and that doesn't happen with HPOneView.300 unless I specify -ManageBoot:$False -BootMode Unmanaged.

What are the corresponding settings with HPOneView.310 if it's not the same combination?

**Comment by ChrisLynchHPE** [comment] 2018-08-07 13:00
The code path has not changed in any of these releases.  It is likely OneView is rejecting or changed validation of the input object.  To help validate this, can you please use `Get-HPOVCommandTrace` to capture verbose output and supply that?

**Comment by ChrisLynchHPE** [comment] 2018-09-18 20:07
Closing due to no further activity and inability to reproduce the reported issue.  If this issue still exists for you, we can re-open the issue.  I will need the captured output from the `Get-HPOVCommandTrace` Cmdlet.

**Closed by ChrisLynchHPE** 2018-09-18 20:07 UTC
