### ISSUE TITLE
New-HPOVLdapDirectory -- lets you add the same directory multiple times

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#158] opened 2016-07-28 09:12 UTC
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
New-HPOVLdapDirectory will only let you add the same directory once.

### Actual Behavior
No check for whether the same directory (with a different identifier) is added a number of times (with a different name).

Maybe there can be some validation on the base DN or the Servers' domain name, e.g. if base dn is the same as something already added, drop it

### Steps to reproduce
New-HPOVLdapDirectory -Name Test -AD -BaseDN <basedn> -Servers $(New-HPOVLDAPServer SERVER) -user <USER> -Password <securestring>

The same parameters can be used ad infinitum as long as you change the "name" parameter although the directory is the same and you'll have a number of directories that are identical except for the name identifier.

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.530.1 (says 2.0.530.5 in appwiz)
HPE OneView Appliance Version: 2.00.07

**Comment by ChrisLynchHPE** [comment] 2016-07-28 15:22
This is by design. There are no restrictions to adding a Directory multiple times with a a different display name but same base DN. This is not a bug. Closing.

**Closed by ChrisLynchHPE** 2016-07-28 15:22 UTC
