### ISSUE TITLE
Cmdlets not outputting as expected

### ISSUE THREAD

**Issue by kataphract** [HewlettPackard/POSH-HPOneView#276] opened 2017-06-14 19:49 UTC
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
I'm trying to pull information about each server in our Synergy cabinets as well as its physical location (Cabinet, Enclosure, Bay).  For example, The command 'Get-HPOVServer' yields this output:

```PowerShell
Name                 Status Power Serial Number Model       ROM                    iLO       Server Profile License      
----                 ------ ----- ------------- -----       ---                    ---       -------------- -------      
CAB1, bay 1 OK     Off   MXxxxxxxxx    SY 480 Gen9 I37 v2.40 (02/17/2017) iLO4 2.53 TESTSRV NotApplicable
```
If I assign it to a variable, ($server = Get-HPOVServer) I would expect to be able to retrieve specific columns like this:

```PowreShell
$server.Name equals 'CAB1, bay 1'
$server.Status equals 'OK'
$server.Power equals 'Off'
#etc.
```
### Actual Behavior
I'm noticing that isn't the case for all columns.  In the given example, If I were to try to retrieve each column header as the output shows (assuming spaces are removed), the result is this:

```PowerShell
$server | Select Name, Status, Power, SerialNumber, Model, ROM, iLO, ServerProfile, License

name          : CAB1, bay 1
status        : OK
Power         : 
serialNumber  : MXxxxxxxxx
model         : Synergy 480 Gen9
ROM           : 
iLO           : 
ServerProfile : 
License       : 
```
running a "$server | get-member" command shows me some of the alternate names but not all, so:

name          : CAB1, bay 1
status        : OK
Power         :  (is listed as powerState)
serialNumber  : MXxxxxxxxx
model         : Synergy 480 Gen9
ROM           :  (is listed as romVersion)
iLO           :  (is listed as mpModel?)
ServerProfile : (is not listed, only serverProfileUri is listed)
License       :  (is not listed, only licensingIntent is listed)

This is only one cmdlet but I'm certain I've seen this behavior on others as well.  Will this be fixed in 3.10?

### Steps to reproduce
save the command's output to a variable and try to retrieve each column separately

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):
PowerShellLibraryVersion : 3.0.1293.3770
LibraryPath              : C:\Program Files\WindowsPowerShell\Modules\HPOneView.300

HPE OneView Appliance Version:  
Synergy Composer 3.00.07-0288219

Output from `$PSVersionTable` on your Windows Host:
Name                           Value                                                                                                                          
----                           -----                                                                                                                          
PSVersion                      5.1.14393.1198                                                                                                                 
PSEdition                      Desktop                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                        
BuildVersion                   10.0.14393.1198                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                                
WSManStackVersion              3.0                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                            
SerializationVersion           1.1.0.1

**Comment by ChrisLynchHPE** [comment] 2017-06-14 20:13
What you see is correct, and is currently by design for the OneView library.  The output of Get-HPOV Cmdlets return the API object, with it's API properties, in a custom Format view.  I have been looking to create my own JSON parser, to then provide PowerShell/C# strongly typed objects, which would then resolve what you are asking about.

**Comment by kataphract** [comment] 2017-06-14 20:18
Good luck, that will help out a lot.

**Comment by ChrisLynchHPE** [comment] 2017-06-14 20:26
In the meantime, if you need to get specific server profile resources from hardware, you can always pass in `Get-HPOVServer` results into `Get-HPOVServerProfile` via the `-InputObject` parameter.  It is documented in the Cmdlet help.

**Comment by kataphract** [comment] 2017-06-14 20:47
That gives me what I need.  Thank you.

**Comment by ChrisLynchHPE** [comment] 2017-08-18 17:35
Closing due to no further activity.

**Closed by ChrisLynchHPE** 2017-08-18 17:35 UTC
Labels: Question
