### ISSUE TITLE
Issue with Invoke-HPOVVcmMigration

### ISSUE THREAD

**Issue by tlauder** [HewlettPackard/POSH-HPOneView#349] opened 2018-07-24 13:39 UTC
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Migration from VCEM to HPE OneView 4.10

### Actual Behavior
Migration from VCEM to HPE OneView 4.10 Fails.

### Steps to reproduce

```PowerShell

Invoke-HPOVVcmMigration -OAIPAddress <OAIP> -OAUserName <OA USER> -OAPassword <OA PASSWORD> -VCMUserName <OA USER> -VCMPassword <VC PASSWORD> -licensingIntent OneView -VCEMCMS vcem.host.com -VCEMUser DOMAIN\USERNAME

WARNING: Enclosure is currently managed by Virtual Connect Enterprise Manager.

Migration Compatibility Report
------------------------------


type                   uri                                                              category              eTag                                 crea
                                                                                                                                                   ted
----                   ---                                                              --------              ----                                 ----
MigratableVcDomainV300 /rest/migratable-vc-domains/284fb634-aefd-4e4e-b5ff-d633acd63926 migratable-vc-domains 1c8540a6-3ab5-4896-9899-8db9c18e1d50 2018
                                                                                                                                                   -07-
                                                                                                                                                   24T1
                                                                                                                                                   2:41
                                                                                                                                                   :25.
                                                                                                                                                   803Z



type                   uri                                                              category              eTag                                 crea
                                                                                                                                                   ted
----                   ---                                                              --------              ----                                 ----
MigratableVcDomainV300 /rest/migratable-vc-domains/284fb634-aefd-4e4e-b5ff-d633acd63926 migratable-vc-domains 1c8540a6-3ab5-4896-9899-8db9c18e1d50 2018
                                                                                                                                                   -07-
                                                                                                                                                   24T1
                                                                                                                                                   2:41
                                                                                                                                                   :25.
                                                                                                                                                   803Z




severity       : Critical
description    : The specified enclosure is managed by Virtual Connect Enterprise Manager (VCEM). It is not possible to migrate the specified
                 enclosure while it is managed by VCEM.
recommendation : Use the VCEM web user interface to remove the Virtual Connect domain from the Virtual Connect domain group before migrating the
                 domain into OneView.
name           : General
resourceName   : General

severity       : Medium
description    : There are 0 HPE OneView Advanced licenses available but 2 servers will require licenses when migrated.
recommendation : Ensure 2 additional licenses are added to OneView.
name           : General
resourceName   : General

severity       : Medium
description    : The domain has advanced network settings port throughput statistics disabled.
recommendation : The setting Advanced Network Settings Throughput Statistics has a value Disabled which is not supported by OneView. The value will be
                 automatically changed to Enabled.
name           : General
resourceName   : General

severity       : High
description    : Profile connections configured with SR-IOV settings for C7000 enclosures are not supported by OneView. The SR-IOV configuration for
                 this powered server will change to evenly distribute VFs across all the FlexNICs once the server is rebooted after migration.
recommendation : Ensure that the server does not depend on the current SR-IOV configuration before proceeding. Change the SR-IOV configuration for
                 Ethernet connection(s)  to "DISABLED" or "AUTO".
name           : Server Profiles
resourceName   : XSPE10B169W

severity       : High
description    : Profile connections configured with SR-IOV settings for C7000 enclosures are not supported by OneView. The SR-IOV configuration for
                 this powered server will change to evenly distribute VFs across all the FlexNICs once the server is rebooted after migration.
recommendation : Ensure that the server does not depend on the current SR-IOV configuration before proceeding. Change the SR-IOV configuration for
                 Ethernet connection(s)  to "DISABLED" or "AUTO".
name           : Server Profiles
resourceName   : XSPE11W836T

Get-Date : Cannot bind parameter 'Date'. Cannot convert value "%T"" to type "System.DateTime". Error: "String was not recognized as a valid DateTime."
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.400\HPOneView.400.psm1:37140 char:135
+ ... Name.ToString().ToUpper(), (get-date -UFormat `"%Y-%m-%d %T`"), $oaUr ...
+                                                              ~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Date], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.GetDateCommand

Invoke-HPOVVcmMigration : The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
At line:1 char:1
+ Invoke-HPOVVcmMigration -OAIPAddress x.x.x.x -OAUserName <OA/VC USER>  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (OAIP:String) [Invoke-HPOVVcmMigration], VcMigratorException
    + FullyQualifiedErrorId : WebException,Invoke-HPOVVcmMigration

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`): 4.0.1672.1789  C:\Program Files\WindowsPowerShell\Modules\HPOneView.400
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  4.10.01-0348545
Output from `$PSVersionTable` on your Windows Host:

```PowerShell
# Output from $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.2312
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2312
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by ChrisLynchHPE** [comment] 2018-07-25 21:49
So, there are a few different issues here:

1. The error with `Get-Date` is due to a module wide change in code cleanup and refactoring verbose output data.  That is an easy fix.
2. There is an issue with the HTTPS certificate of the VCEM host.  In order to troubleshoot that further, I'll need the output from `Get-HPOVCommandTrace`:

``PowerShell
$ScriptBlock = { Invoke-HPOVVcmMigration -OAIPAddress <OAIP> -OAUserName <OA USER> -OAPassword <OA PASSWORD> -VCMUserName <OA USER> -VCMPassword <VC PASSWORD> -licensingIntent OneView -VCEMCMS vcem.host.com -VCEMUser DOMAIN\USERNAME }
Get-HPOVCommandTrace -ScriptBlock $ScriptBlock
```

**Comment by tlauder** [comment] 2018-07-27 08:37
Hey Chris,

We are having issues freeing up chassis to get you the information you need. I will hopefully get back to you soon with the info.

Thanks,
Todd

**Comment by ChrisLynchHPE** [comment] 2018-07-27 16:44
Thanks Todd.  I'll also see if I can get someone internally to help reproduce the condition with connecting to a VCEM host to initiate VC Domain removal from VCEM Domain Group.

**Comment by ChrisLynchHPE** [comment] 2018-07-27 16:50
Also, can you go to your VCEM host and validate if the SSL certificate has expired, or verify that the Issuer and Subject Name are the same (that is how we validate if a cert is self-signed or not).

**Comment by ChrisLynchHPE** [comment] 2018-09-18 20:08
@tlauder can you provide any further status update on this?

**Comment by tlauder** [comment] 2018-09-27 18:44
@ChrisLynchHPE - Sorry, I haven't been able to find chassis that I can use to re-test this. I'll assume you can close the issue, and when I get a chance I will re-test.

Thanks!
Todd

**Comment by ChrisLynchHPE** [comment] 2018-09-27 18:50
Okay.  I'm closing this.  If you happen to run into this again, please provide the information I requested above and we can then re-open the issue.

**Closed by ChrisLynchHPE** 2018-09-27 18:50 UTC
Labels: 4.10, Bug
