### ISSUE TITLE
Get-HPOVServerProfileConnectionList returning error

### ISSUE THREAD

**Issue by stdb** [HewlettPackard/POSH-HPOneView#333] opened 2018-04-24 12:57 UTC
Please fill in as much information as possible to help resolve your issue.

Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Get-HPOVServerProfileConnectionList returning a list of profile connections.

### Actual Behavior
```PowerShell
PS C:\icts\CEIF_DC\hp_svn> Get-HPOVServerProfileConnectionList
Get-HPOVServerProfileConnectionList : Cannot validate argument on parameter 'uri'. -URI must being with a '/' (eg. /rest/server-hardware) in its value. Please correct the value and try again.
At line:1 char:1
+ Get-HPOVServerProfileConnectionList
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-HPOVServerProfileConnectionList], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Get-HPOVServerProfileConnectionList
```
### Steps to reproduce
Connect to oneview appliance, using connect-hpovmgt (4.00 library).
Execute Get-HPOVServerProfileConnectionList.

[Get-HPOVServerProfileConnectionList_verboseOutput.zip](https://github.com/HewlettPackard/POSH-HPOneView/files/1942813/Get-HPOVServerProfileConnectionList_verboseOutput.zip)

# Output from $PSVersionTable
```PowerShell
Name  : PSVersion
Value : 4.0

Name  : WSManStackVersion
Value : 3.0

Name  : SerializationVersion
Value : 1.1.0.1

Name  : CLRVersion
Value : 4.0.30319.42000

Name  : BuildVersion
Value : 6.3.9600.18773

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0}

Name  : PSRemotingProtocolVersion
Value : 2.2
```

**Comment by ChrisLynchHPE** [comment] 2018-04-24 17:28
Hmm..  I'm not able to reproduce the error.  When you do encounter it, can you do the following and provide the output:

```PowerShell

$error | ? Message -match "Cannot validate argument on parameter 'uri'" | % {

    Format-List -InputObject $_ -Property * -Force

}
```

**Comment by ChrisLynchHPE** [comment] 2018-05-03 04:35
Can you provide any further detail on this?

**Comment by ChrisLynchHPE** [comment] 2018-09-18 20:39
Closing due to no further activity.

**Closed by ChrisLynchHPE** 2018-09-18 20:39 UTC
