### ISSUE TITLE
Bandwidth per Flexible LOM in Oneview Server Profile

### ISSUE THREAD

**Issue by 5truja** [HewlettPackard/POSH-HPOneView#98] opened 2016-04-19 06:38 UTC
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
I have two Uplinks (each 10Gbps). I created two Network Set on one of the uplinks (A and B side)
On the other Uplink I created tunnel.

### Actual Behavior
When creating server profile template I can create only max 10Gbps distributed over 4 (or 8 A an B side) Flexible LOMs. In VC/VCEM i could present (end to end let's say in hypervisor) 10Gbps per NIC team but not in OV since it does not allow med to go over 10Gbps in total. What is the catch here? 

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):
HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:

**Comment by ChrisLynchHPE** [comment] 2016-04-19 15:14
This is not a bug with the HPE OneView POSH Library, nor is a bug with the HPE OneVeiw appliance.  We currently do not support over provisioning like we do with Virtual Connect Manager (VCM).  Over-provisioning inVCM will not allow an interface to be set at the value you set anyhow.  All of the interfaces will get a proportional value of the bandwidth based on their requested value to the aggregate of the defined FlexNICs.

**Comment by 5truja** [comment] 2016-04-19 15:41
I would not call that “overprovisioned” (it’s hypothetical question of course), since one Network set Is connected to 2x10Gbps (X2) ethernet uplink and share that very same uplink with another Network set. The third (TUNNEL) is connected to anoTher 2x10Gbps (A-B and X3 Ethernet uplink). Så basically oneview is limiting ESXi to use available bandwidth which would be fine to use since we separate hypervisor (X2 ) and VM guest (X3) stacks.
So you mean there is no other way that configure as 10GBbps in total per serverprofile, which is strange since Net Set is having 20Gbps as max bandwidth value (?).

**Comment by ChrisLynchHPE** [comment] 2016-04-19 17:43
I think you have a misunderstanding of how Bandwidth is assigned and how it affects (or doesn't affect) other resources.

An `Uplink Set` defines how the `Uplink Ports` should be connected at, to the upstream fabric infrastructure.  It does not adjust, or directly impact the value of the `Requested Bandwidth` you can set at the other resources; `Networks`, `Network Sets` and `Server Profile Connections`

A `Network` represents a L2 fabric, which is then assigned to a `Server Profile Connection`.  The `Preferred` and `Maximum` bandwidth values define what are the Min and Max Bandwidth values that a `Server Profile Connection` can request.  So, if I set the `Preferred` to say 3Gbps, and the `Maximum` to 5Gbps, assign it to a Server Profile Connection without specifying any bandwidth, the Connection will request the 3Gbps value.  If I set the value to 5.5Gbps instead, the request will fail because the value is greater than 5Gbps.  Either value has no impact on the `Uplink Set` assigned `Uplink Port(s)`.

A `Network Set` is a collection of `Ethernet Networks` to define an 802.1Q Trunk port on the `Downlink Ports`, which then map by assignment to the `Server Profile Connection`.  The same behavior with `Networks` applies here.  What could be confusing is that the assigned `Ethernet Networks` Bandwidth allocation within the `Network Set` is actually overriden by the `Network Set` bandwidth values.

A `Server Profile Connection` has a similar `Preferred` Bandwidth value, but it is called `Requested`.  Bandwidth in the `Server Profile Connection` isn't assigned or allocated until the `Create Server Profile` task is validated.  

So let's take the following as an example:

* `VLAN 1` has `Preferred Bandwidth` set to `2Gbps`, and `Maximum Bandwidth` set to `5Gbps`.
* `VM Network 100`, `VM Network 101`, `VM Network 102`, `VM Network 103` are assigned to `Virtual Machine Set`, with `Preferred Bandwidth` set to `8Gbps`, and `Maximum Bandwidth` set to `8Gbps`.
* `Migration Network` has `Preferred Bandwidth` set to `2Gbps`, and `Maximum Bandwidth` set to `2Gbps`.

I then attempt to go assign all of the Network resources as follows, using default bandwidth values:

* `FlexLOM1:A` = `VLAN 1` [Requested Bandwidth is 2Gbps]
* `FlexNIC2:A` = `VLAN 1` [Requested Bandwidth is 2Gbps]
* `FlexLOM1:B` = `Virtual Machine Set` [Requested Bandwidth is 8Gbps]
* `FlexLOM2:B` = `Virtual Machine Set` [Requested Bandwidth is 8Gbps]
* `FlexLOM1:C` = `Migration Network` [Requested Bandwidth is 2Gbps]
* `FlexLOM2:C` = `Migration Network` [Requested Bandwidth is 2Gbps]

The Server Profile Create request will fail.  Why?  Because the aggregate Bandwidth request is 12Gbp per Physical 10Gb port.  We call this oversubscription.  To fix this, I would need to adjust the `Virtual Machine Set` `Requested Bandwidth` value to less than `8Gbp`. 


In Virtual Connect Manager, we would give a proportional value to each requested `Connection`, resulting in the following new `Allocated` assignment using `(Requested Bandwidth / Aggregate Bandwidth * Total Port Speed Capacity)` formula:

* `FlexLOM1:A` = `VLAN 1` [Bandwidth Allocation is 1.6Gbps]
* `FlexLOM2:A` = `VLAN 1` [Bandwidth Allocation is 1.6Gbps]
* `FlexLOM1:B` = `Virtual Machine Set` [Bandwidth Allocation is 6.6Gbps]
* `FlexLOM2:B` = `Virtual Machine Set` [Bandwidth Allocation is 6.6Gbps]
* `FlexLOM1:C` = `Migration Network` [Bandwidth Allocation is 1.6Gbps]
* `FlexLOM2:C` = `Migration Network` [Bandwidth Allocation is 1.6Gbps]

We also introduced a feature in VCM called `Mix/Max Bandwidth`.  This allows you to set the maximum Bandwidth value possible for the `Connection`.  We implemented a time sharing mechanism to allow other `Connections` to burst or consume all of the bandwidth allocated.  Think of this as a similar concept to VMware `Shares`.  If the `Share` is equal, then all have equal share to the source, but one could consume all of the available `Shares`.  This is another way to oversubscribe.

HPE OneView does not currently support Oversubscription.  You must define the Requested Bandwidth to not exceed the maximum aggregate of the FlexNICs from the same physical port (e.g. `FlexLOM1:A`, `FlexLOM1:B`, `FlexLOM1:C`, and `FlexLOM1:D` aggregate cannot exceed 10Gbp for a FlexFabric or Flex-10 Adapter).

**Comment by 5truja** [comment] 2016-04-20 07:28
Great elaboration and thank you for that.


> HPE OneView does not currently support Oversubscription. You must define the Requested Bandwidth to not exceed the maximum aggregate of the FlexNICs from the same physical port (e.g. FlexLOM1:A, FlexLOM1:B, FlexLOM1:C, and >FlexLOM1:D aggregate cannot exceed 10Gbp for a FlexFabric or Flex-10 Adapter).

This is a bit disappointing since today in VCEM environment I can connect my mgmt networks to separate uplink (X2) and use all 10Gbps in server profile and also VMs to another (X3) and use 10Gbps.

We are using multiple VMotion IP addresses too (since vSphere 5 ) having which makes migrations and maintenance mode operations much faster. I need test this in OV environment and compare. I hope it will do.

> So, if I set the Preferred to say 3Gbps, and the Maximum to 5Gbps, assign it to a Server Profile Connection without specifying any bandwidth,

Please correct me if I am wrong but it sounds like that I could create Server Profile without specifying bandwidth (AND not using Network Set but only Multiple Networks like in VCEM case) and get another behavior regarding total bandwidth?

However I do not see that creating server profile (in GUI at least) is possible without bandwidth parameter.

**Comment by ChrisLynchHPE** [comment] 2016-04-22 19:03
> This is a bit disappointing since today in VCEM environment I can connect my mgmt networks to separate uplink (X2) and use all 10Gbps in server profile and also VMs to another (X3) and use 10Gbps.

Except you are not using 2 x 10Gbps.  Your adapter has two physical ports (if we take the 554flb adapter as an example), each with a max connection of 10Gbps.  VCM/VCEM allows for oversubscription, so that if a FlexNIC has no activity (or very little), other FlexNICs can use more bandwidth.  This is similar to the VMware Shares capability I mentioned above.  However, none of the FlexNICs can go beyond 10Gbps.  And the aggregate bandwidth with all FlexNICs (A, B, C, and D) from the same physical port (FLB1) cannot exceed 10Gbps anyhow.

> We are using multiple VMotion IP addresses too (since vSphere 5 ) having which makes migrations and maintenance mode operations much faster. I need test this in OV environment and compare. I hope it will do.

Yes, you can configure multiple Interfaces to different VMotion networks within OneView.  You have the same Network allocation restrictions in OneView as you do with VCM/VCEM.

> Please correct me if I am wrong but it sounds like that I could create Server Profile without specifying bandwidth (AND not using Network Set but only Multiple Networks like in VCEM case) and get another behavior regarding total bandwidth?

No.  The `Multiple Networks` option is replaced by `Network Sets` within HPE OneView.  You would get the exact same bandwidth allocation behavior with `Network Sets` as you do with `Multiple Networks` in VCM/VCEM.

> However I do not see that creating server profile (in GUI at least) is possible without bandwidth parameter.

You still need to provide a Requested Bandwidth value in the Server Profile.  `Ethernet Connections` always default to `2.5Gbps`.

**Comment by 5truja** [comment] 2016-04-22 19:10
Hi Chris,

Thanks again for clarifying all differences between VCEM and OV.

Kind regards and have a nice weekend

Med v?nlig h?lsning,
Mladen Brekalo


22 apr. 2016 kl. 21:03 skrev Chris Lynch <notifications@github.com<mailto:notifications@github.com>>:


This is a bit disappointing since today in VCEM environment I can connect my mgmt networks to separate uplink (X2) and use all 10Gbps in server profile and also VMs to another (X3) and use 10Gbps.

Except you are not using 2 x 10Gbps. Your adapter has two physical ports (if we take the 554flb adapter as an example), each with a max connection of 10Gbps. VCM/VCEM allows for oversubscription, so that if a FlexNIC has no activity (or very little), other FlexNICs can use more bandwidth. This is similar to the VMware Shares capability I mentioned above. However, none of the FlexNICs can go beyond 10Gbps. And the aggregate bandwidth with all FlexNICs (A, B, C, and D) from the same physical port (FLB1) cannot exceed 10Gbps anyhow.

We are using multiple VMotion IP addresses too (since vSphere 5 ) having which makes migrations and maintenance mode operations much faster. I need test this in OV environment and compare. I hope it will do.

Yes, you can configure multiple Interfaces to different VMotion networks within OneView. You have the same Network allocation restrictions in OneView as you do with VCM/VCEM.

Please correct me if I am wrong but it sounds like that I could create Server Profile without specifying bandwidth (AND not using Network Set but only Multiple Networks like in VCEM case) and get another behavior regarding total bandwidth?

No. The Multiple Networks option is replaced by Network Sets within HPE OneView. You would get the exact same bandwidth allocation behavior with Network Sets as you do with Multiple Networks in VCM/VCEM.

However I do not see that creating server profile (in GUI at least) is possible without bandwidth parameter.

You still need to provide a Requested Bandwidth value in the Server Profile. Ethernet Connections always default to 2.5Gbps.

-

**Comment by ChrisLynchHPE** [comment] 2016-04-22 19:21
No problem.  Closing.

**Closed by ChrisLynchHPE** 2016-04-22 19:21 UTC
Labels: Question
