### ISSUE TITLE
Ping-hpovaddress many error messages

### ISSUE THREAD

**Issue by jonathan7777** [HewlettPackard/POSH-HPOneView#84] opened 2016-03-24 15:48 UTC
i tried a ping with the example described in the get-help of the cmdlet.
in the cmdlet there is no "status" parameter available.

Write-Progress : Cannot validate argument on parameter 'Status'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:44353 char:106
+ ... ame))" -status $progressStatus -percentComplete $taskObj.percentComplete
+                    ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Progress], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.WriteProgressCommand
 
Write-Progress : Cannot validate argument on parameter 'Status'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:44353 char:106
+ ... ame))" -status $progressStatus -percentComplete $taskObj.percentComplete
+                    ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Progress], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.WriteProgressCommand
 
Write-Progress : Cannot validate argument on parameter 'Status'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:44353 char:106
+ ... ame))" -status $progressStatus -percentComplete $taskObj.percentComplete
+                    ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Progress], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.WriteProgressCommand
 
Write-Progress : Cannot validate argument on parameter 'Status'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:44353 char:106
+ ... ame))" -status $progressStatus -percentComplete $taskObj.percentComplete
+                    ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Progress], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.WriteProgressCommand
 
Write-Progress : Cannot validate argument on parameter 'Status'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:44353 char:106
+ ... ame))" -status $progressStatus -percentComplete $taskObj.percentComplete
+                    ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Progress], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.WriteProgressCommand
 
Write-Progress : Cannot validate argument on parameter 'Status'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:44353 char:106
+ ... ame))" -status $progressStatus -percentComplete $taskObj.percentComplete
+                    ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Progress], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.WriteProgressCommand
 
Write-Progress : Cannot validate argument on parameter 'Status'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:44353 char:106
+ ... ame))" -status $progressStatus -percentComplete $taskObj.percentComplete
+                    ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Progress], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.WriteProgressCommand
 
Write-Progress : Cannot validate argument on parameter 'Status'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:44353 char:106
+ ... ame))" -status $progressStatus -percentComplete $taskObj.percentComplete
+                    ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Progress], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.WriteProgressCommand
 
Write-Progress : Cannot validate argument on parameter 'Status'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:44353 char:106
+ ... ame))" -status $progressStatus -percentComplete $taskObj.percentComplete
+                    ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Progress], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.WriteProgressCommand
 
Write-Progress : Cannot validate argument on parameter 'Status'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:44353 char:106
+ ... ame))" -status $progressStatus -percentComplete $taskObj.percentComplete
+                    ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Progress], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.WriteProgressCommand

**Comment by ChrisLynchHPE** [comment] 2016-03-24 17:19
This is a defect found in `Wait-HPOVTaskComplete`, not `Ping-HPOVAddress`, and isn't due to your Cmdlet call.  I found the cause, and will be fixed in the next update.

**Comment by ChrisLynchHPE** [comment] 2016-04-09 00:06
Fixed in the [2.0.310.0] (https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.310.0) release.

**Closed by ChrisLynchHPE** 2016-04-09 00:06 UTC
Labels: Bug, Impact - Low
