### ISSUE TITLE
Get-HPOVServerProfileTemplate Result

### ISSUE THREAD

**Issue by CermakPOI** [HewlettPackard/POSH-HPOneView#171] opened 2016-09-21 09:43 UTC
Please fill in as much information as possible to help resolve your issue.
Get-HPOVServerProfileTemplate does not return the default displayed Results. The properties are not available.
i need to retrieve the "Server Hardware Type". i don NOT need the serverHardwareType**Uri**

### Expected Behavior
```

 Get-HPOVServerProfileTemplate
Name                    Status Server Hardware Type Enclosure Group Affinity Server
----                    ------ -------------------- --------------- -------- -------
PT-ESX-Host-DL380-GEN8  OK     DL380p Gen8 1                                 ESXHOST
PT-ESX-Host-BL460c-GEN8 OK     BL460c Gen8 2        EnclosureGroup1 Bay      {ESXHOS
PT-ESX-Host-DL380-GEN9  OK     DL380 Gen9 1                                  {ESXHOS
PT-ESX-Host-DL580-GEN9  OK     DL580 Gen9 1                                  {ESXHOS
PT-ESX-Host-BL460c-GEN9 OK     BL460c Gen9 1        EnclosureGroup1 Bay      {ESXHOS
 Get-HPOVServerProfileTemplate | select "Server Hardware Type"
Server Hardware Type
------------------
DL380p Gen8 1
BL460c Gen8 2
DL380 Gen9 1
DL580 Gen9 1
BL460c Gen9 1

```
### Actual Behavior
```

Get-HPOVServerProfileTemplate

Name                    Status Server Hardware Type Enclosure Group Affinity Server
----                    ------ -------------------- --------------- -------- -------
PT-ESX-Host-DL380-GEN8  OK     DL380p Gen8 1                                 ESXHOST
PT-ESX-Host-BL460c-GEN8 OK     BL460c Gen8 2        EnclosureGroup1 Bay      {ESXHOS
PT-ESX-Host-DL380-GEN9  OK     DL380 Gen9 1                                  {ESXHOS
PT-ESX-Host-DL580-GEN9  OK     DL580 Gen9 1                                  {ESXHOS
PT-ESX-Host-BL460c-GEN9 OK     BL460c Gen9 1        EnclosureGroup1 Bay      {ESXHOS
 Get-HPOVServerProfileTemplate | select "Server Hardware Type"
ServerHardwareType
------------------






```
```
PS C:\Users\admcer> Get-HPOVServerProfileTemplate | fl *


type                     : ServerProfileTemplateV1
uri                      : /rest/server-profile-templates/21c00faa-2db4-4a5f-9595-3a1042a83619
name                     : PT-ESX-Host-DL380-GEN8
description              : Server Profile (BIOS Settings) for rack mounted ESXi Hosts
serverProfileDescription : VMware ESXi Server
serverHardwareTypeUri    : /rest/server-hardware-types/18BC03E2-B7F7-4909-842B-9F351765819B
enclosureGroupUri        :
affinity                 :
hideUnusedFlexNics       :
macType                  : Physical
wwnType                  : Physical
serialNumberType         : Physical
firmware                 : @{manageFirmware=False; firmwareInstallType=; forceInstallFirmware=False; firmwareBaselineUri=}
....
```
### Steps to reproduce
Connect to HPOV Appliance

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.621.0
HPE OneView Appliance Version:  2.00.02-0219211
Output from `$PSVersionTable` on your Windows Host:
Name  : PSVersion
Value : 4.0

Name  : WSManStackVersion
Value : 3.0

Name  : SerializationVersion
Value : 1.1.0.1

Name  : CLRVersion
Value : 4.0.30319.42000

Name  : BuildVersion
Value : 6.3.9600.17400

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0}

Name  : PSRemotingProtocolVersion
Value : 2.2

**Comment by ChrisLynchHPE** [comment] 2016-09-21 15:42
This is by design.  All objects are in their deflated state.  Meaning, any associations a resource could have will simply contain the URI reference, and not a full inflated object.  This is how the HPE OneView REST API operates.

Can you explain what it is you're trying to accomplish (besides getting the SHT for a Server Profile Template)?

**Comment by CermakPOI** [comment] 2016-09-22 08:41
I need to reference the SHT for a Migration from VCEM to OV to get the ProfileTemplate to join the profile to the template.
In the default formating you disply what i need! I need you to just return the values in the object also.

**Comment by ChrisLynchHPE** [comment] 2016-09-22 15:40
Do you need the SHT object?  You can always do the following:

```PowerShell
$SHT = Send-HPOVRequest -Uri (Get-HPOVServerProfileTemplate -Name 'My Template Name').serverHardwareTypeUri
$SHT.name
```

Can you share the code you are trying to develop?

**Comment by CermakPOI** [comment] 2016-09-27 08:55
I have a really easy requirement which should be supported Powershell Style:
I want to get the Profile Template for a specific Server Hardware Type.

```
$ProfileNowHardware = "ProLiant BL460c Gen8"
$filterServerHW = $ProfileNowHardware.Substring(9) + "*"
$MyHW = Get-HPOVServerHardwareType | Where-Object { ($_.name -like $filterServerHW) -and ($_.Adapters -like "*HBA*")}
$objProfileTemplate = Get-HPOVServerProfileTemplate | Where-Object { $_."Server Hardware Type" -like $filterServerHW }
```

**Comment by ChrisLynchHPE** [comment] 2016-09-27 16:03
You would do the following instead:

```PowerShell
$ProfileNowHardware = "ProLiant BL460c Gen8"
$filterServerHW = $ProfileNowHardware.Substring(9) + "*"
$MyHW = Get-HPOVServerHardwareType | Where-Object { ($_.name -like $filterServerHW) -and ($_.Adapters -like "*HBA*")}
$objProfileTemplate = Get-HPOVServerProfileTemplate | Where-Object { $_.serverHardwareTypeUri -eq $MyHW.uri}
```

**Comment by CermakPOI** [comment] 2016-09-29 08:24
Thank you for the workaround!

It would be easier if the design would be more powershell native. Since you already display it in the default formatting it's really confusing! And it would be easy to just add a new property in inflated state,

**Comment by ChrisLynchHPE** [comment] 2016-09-29 15:54
Except this is PowerShell native.  The properties are just not exposed by default, just like say a `WMI` object is when you use `Get-NetAdapter`.  Objects are used through out the library, and we can't just inflate all objects right now.  We are working through some ideas on how to accomplish this, but it's not part of the library right now.

**Comment by CermakPOI** [comment] 2016-10-04 08:03
Well, the difference is the usability! I'm not talking about default formated hidden objects. If it's displayed in the default formatting i can use it straight away in PS and 3rd party tools like PowerCLi,
With Get-NetAdapter i can reference all displayed data directly, i don't have to care about underlaying WMI Paths:

```
PS U:\> Get-NetAdapter | where InterfaceDescription -like "Blue*"

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
Bluetooth-Netzwerkverb... Bluetooth Device (Personal Area Netw...      13 Disconnected B8-8A-60-55-EA-2D         3 Mbps
```

**Comment by ChrisLynchHPE** [comment] 2016-10-04 16:03
You missed my point.  There are plenty of Cmdlets (both native Microsoft and 3rd party) that use custom Format displays that hide other uncommon properties.  As I stated above, it is not an easy implementation to inflate every object to include other objects.  This is why other Cmdlets accept objects during Cmdlet execution (like `New-HPOVServerProfile` accepts Enclosure Groups, Server Hardware, Networks, etc. objects).

I have enhanced `Get-HPOVServer` to include a `-ServerHardwareType` so you can filter your server hardware inventory using a Name or Object of a Server Hardware Type resource, along with the `-NoProfile` parameter.

**Comment by ChrisLynchHPE** [comment] 2016-10-27 06:34
The enhanced version of Get-HPOVServer has been published.  It is in [Release 2.0.630.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.630.0).

Closing.

**Closed by ChrisLynchHPE** 2016-10-27 06:34 UTC
